使用create_cistarget_motif_databases.py构建cisTarget数据库前的准备工作： 生成create_cistarget_motif_databases.py -f参数对应的fasta文件

In [1]:
%%bash

mkdir -p "./fasta"
wget -O "./fasta/Apis_mellifera.fasta.gz" "https://ftp.ensemblgenomes.ebi.ac.uk/pub/metazoa/current/fasta/apis_mellifera/dna/Apis_mellifera.Amel_HAv3.1.dna.toplevel.fa.gz"
gunzip "./fasta/Apis_mellifera.fasta.gz"

--2026-08-12 16:15:40--  https://ftp.ensemblgenomes.ebi.ac.uk/pub/metazoa/current/fasta/apis_mellifera/dna/Apis_mellifera.Amel_HAv3.1.dna.toplevel.fa.gz
Resolving ftp.ensemblgenomes.ebi.ac.uk (ftp.ensemblgenomes.ebi.ac.uk)... 193.62.193.161
Connecting to ftp.ensemblgenomes.ebi.ac.uk (ftp.ensemblgenomes.ebi.ac.uk)|193.62.193.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66731516 (64M) [application/x-gzip]
Saving to: './fasta/Apis_mellifera.fasta.gz'

     0K .......... .......... .......... .......... ..........  0% 84.0K 12m55s
    50K .......... .......... .......... .......... ..........  0%  126M 6m28s
   100K .......... .......... .......... .......... ..........  0%  167K 6m28s
   150K .......... .......... .......... .......... ..........  0%  140M 4m51s
   200K .......... .......... .......... .......... ..........  0%  169K 5m10s
   250K .......... .......... .......... .......... ..........  0% 51.0M 4m18s
   300K .......... .......... .......... .......... ..........  0%  138M 3m41s
   350K .......... .......... .......... .......... ..........  0%  170K 4m1s
   400K .......... .......... .......... .......... ..........  0% 40.1M 3m34s
   450K .......... .......... .......... .......... ..........  0% 41.0M 3m13s
   500K .......... .......... .......... .......... ..........  0% 67.5M 2m55s
   550K .......... .......... .......... .......... ..........  0% 55.5M 2m41s
   600K .......... .......... .......... .......... ..........  0% 64.4M 2m28s
   650K .......... .......... .......... .......... ..........  1% 41.5M 2m18s
   700K .......... .......... .......... .......... ..........  1%  172K 2m33s
   750K .......... .......... .......... .......... ..........  1% 35.3M 2m24s
   800K .......... .......... .......... .......... ..........  1% 40.8M 2m15s
   850K .......... .......... .......... .......... ..........  1% 34.3M 2m8s
   900K .......... .......... .......... .......... ..........  1% 63.9M 2m1s
   950K .......... .......... .......... .......... ..........  1% 85.1K 2m33s
  1000K .......... .......... .......... .......... ..........  1% 71.0M 2m25s
  1050K .......... .......... .......... .......... ..........  1%  145M 2m19s
  1100K .......... .......... .......... .......... ..........  1%  137M 2m12s
  1150K .......... .......... .......... .......... ..........  1%  146M 2m7s
  1200K .......... .......... .......... .......... ..........  1%  131M 2m2s
  1250K .......... .......... .......... .......... ..........  1%  147M 1m57s
  1300K .......... .......... .......... .......... ..........  2%  142M 1m53s
  1350K .......... .......... .......... .......... ..........  2%  564K 1m52s
  1400K .......... .......... .......... .......... ..........  2% 36.6M 1m49s
  1450K .......... .......... .......... .......... ..........  2% 50.8M 1m45s
  1500K .......... .......... .......... .......... ..........  2%  155M 1m41s
  1550K .......... .......... .......... .......... ..........  2%  147M 98s
  1600K .......... .......... .......... .......... ..........  2%  127M 95s
  1650K .......... .......... .......... .......... ..........  2%  150M 92s
  1700K .......... .......... .......... .......... ..........  2%  135M 90s
  1750K .......... .......... .......... .......... ..........  2%  152M 87s
  1800K .......... .......... .......... .......... ..........  2%  159M 85s
  1850K .......... .......... .......... .......... ..........  2%  137M 82s
  1900K .......... .......... .......... .......... ..........  2%  149M 80s
  1950K .......... .......... .......... .......... ..........  3%  134M 78s
  2000K .......... .......... .......... .......... ..........  3%  157M 76s
  2050K .......... .......... .......... .......... ..........  3%  151M 74s
  2100K .......... .......... .......... .......... ..........  3%  135M 73s
  2150K .......... .......... .......... .......... ..........  3%  153M 71s
  2200K .......... .......... .......... .......... ..........  3%  128M 69s
  2250K .......... .......... .......... .......... ..........  3%  145M 68s
  2300K .......... .......... .......... .......... ..........  3%  173K 74s
  2350K .......... .......... .......... .......... ..........  3% 44.6M 72s
  2400K .......... .......... .......... .......... ..........  3% 44.9M 71s
  2450K .......... .......... .......... .......... ..........  3% 44.9M 69s
  2500K .......... .......... .......... .......... ..........  3% 52.5M 68s
  2550K .......... .......... .......... .......... ..........  3% 36.3M 67s
  2600K .......... .......... .......... .......... ..........  4% 42.6M 65s
  2650K .......... .......... .......... .......... ..........  4% 40.0M 64s
  2700K .......... .......... .......... .......... ..........  4% 38.5M 63s
  2750K .......... .......... .......... .......... ..........  4% 34.8M 62s
  2800K .......... .......... .......... .......... ..........  4% 53.6M 61s
  2850K .......... .......... .......... .......... ..........  4% 35.6M 60s
  2900K .......... .......... .......... .......... ..........  4% 50.5M 59s
  2950K .......... .......... .......... .......... ..........  4% 55.9M 58s
  3000K .......... .......... .......... .......... ..........  4% 52.8M 57s
  3050K .......... .......... .......... .......... ..........  4% 88.9M 56s
  3100K .......... .......... .......... .......... ..........  4%  178K 60s
  3150K .......... .......... .......... .......... ..........  4% 84.3K 71s
  3200K .......... .......... .......... .......... ..........  4% 51.2M 70s
  3250K .......... .......... .......... .......... ..........  5%  107M 69s
  3300K .......... .......... .......... .......... ..........  5% 99.3M 68s
  3350K .......... .......... .......... .......... ..........  5%  104M 66s
  3400K .......... .......... .......... .......... ..........  5%  134M 65s
  3450K .......... .......... .......... .......... ..........  5% 98.5M 64s
  3500K .......... .......... .......... .......... ..........  5% 78.0M 64s
  3550K .......... .......... .......... .......... ..........  5%  108M 63s
  3600K .......... .......... .......... .......... ..........  5% 91.0M 62s
  3650K .......... .......... .......... .......... ..........  5%  138M 61s
  3700K .......... .......... .......... .......... ..........  5% 68.1M 60s
  3750K .......... .......... .......... .......... ..........  5%  153M 59s
  3800K .......... .......... .......... .......... ..........  5%  108M 58s
  3850K .......... .......... .......... .......... ..........  5% 85.9M 58s
  3900K .......... .......... .......... .......... ..........  6%  107M 57s
  3950K .......... .......... .......... .......... ..........  6% 91.1M 56s
  4000K .......... .......... .......... .......... ..........  6%  105M 55s
  4050K .......... .......... .......... .......... ..........  6%  110M 55s
  4100K .......... .......... .......... .......... ..........  6% 81.3M 54s
  4150K .......... .......... .......... .......... ..........  6%  123M 53s
  4200K .......... .......... .......... .......... ..........  6% 77.3M 53s
  4250K .......... .......... .......... .......... ..........  6%  101M 52s
  4300K .......... .......... .......... .......... ..........  6% 99.1M 51s
  4350K .......... .......... .......... .......... ..........  6% 90.8M 51s
  4400K .......... .......... .......... .......... ..........  6% 83.3M 50s
  4450K .......... .......... .......... .......... ..........  6%  113M 49s
  4500K .......... .......... .......... .......... ..........  6%  134M 49s
  4550K .......... .......... .......... .......... ..........  7%  145M 48s
  4600K .......... .......... .......... .......... ..........  7%  131M 48s
  4650K .......... .......... .......... .......... ..........  7%  133M 47s
  4700K .......... .......... .......... .......... ..........  7%  116M 47s
  4750K .......... .......... .......... .......... ..........  7%  138M 46s
  4800K .......... .......... .......... .......... ..........  7%  146M 46s
  4850K .......... .......... .......... .......... ..........  7%  129M 45s
  4900K .......... .......... .......... .......... ..........  7%  128M 45s
  4950K .......... .......... .......... .......... ..........  7%  136M 44s
  5000K .......... .......... .......... .......... ..........  7%  151M 44s
  5050K .......... .......... .......... .......... ..........  7%  128M 43s
  5100K .......... .......... .......... .......... ..........  7%  127M 43s
  5150K .......... .......... .......... .......... ..........  7%  144M 42s
  5200K .......... .......... .......... .......... ..........  8%  126M 42s
  5250K .......... .......... .......... .......... ..........  8%  144M 42s
  5300K .......... .......... .......... .......... ..........  8%  133M 41s
  5350K .......... .......... .......... .......... ..........  8%  126M 41s
  5400K .......... .......... .......... .......... ..........  8%  151M 40s
  5450K .......... .......... .......... .......... ..........  8% 86.9K 46s
  5500K .......... .......... .......... .......... ..........  8%  102M 46s
  5550K .......... .......... .......... .......... ..........  8% 83.9M 45s
  5600K .......... .......... .......... .......... ..........  8%  123M 45s
  5650K .......... .......... .......... .......... ..........  8% 97.0M 44s
  5700K .......... .......... .......... .......... ..........  8%  109M 44s
  5750K .......... .......... .......... .......... ..........  8% 91.6M 44s
  5800K .......... .......... .......... .......... ..........  8%  105M 43s
  5850K .......... .......... .......... .......... ..........  9%  124M 43s
  5900K .......... .......... .......... .......... ..........  9% 98.0M 42s
  5950K .......... .......... .......... .......... ..........  9% 79.3M 42s
  6000K .......... .......... .......... .......... ..........  9% 94.1M 42s
  6050K .......... .......... .......... .......... ..........  9% 70.5M 41s
  6100K .......... .......... .......... .......... ..........  9% 76.2M 41s
  6150K .......... .......... .......... .......... ..........  9% 97.4M 41s
  6200K .......... .......... .......... .......... ..........  9% 84.2M 40s
  6250K .......... .......... .......... .......... ..........  9%  102M 40s
  6300K .......... .......... .......... .......... ..........  9%  114M 39s
  6350K .......... .......... .......... .......... ..........  9%  110M 39s
  6400K .......... .......... .......... .......... ..........  9% 18.8M 39s
  6450K .......... .......... .......... .......... ..........  9% 16.8M 39s
  6500K .......... .......... .......... .......... .......... 10% 22.2M 38s
  6550K .......... .......... .......... .......... .......... 10%  179K 40s
  6600K .......... .......... .......... .......... .......... 10% 32.7M 40s
  6650K .......... .......... .......... .......... .......... 10% 13.9M 40s
  6700K .......... .......... .......... .......... .......... 10% 20.7M 39s
  6750K .......... .......... .......... .......... .......... 10% 33.7M 39s
  6800K .......... .......... .......... .......... .......... 10%  133K 42s
  6850K .......... .......... .......... .......... .......... 10%  115M 42s
  6900K .......... .......... .......... .......... .......... 10%  148M 41s
  6950K .......... .......... .......... .......... .......... 10%  123M 41s
  7000K .......... .......... .......... .......... .......... 10%  149M 41s
  7050K .......... .......... .......... .......... .......... 10%  155M 40s
  7100K .......... .......... .......... .......... .......... 10%  118M 40s
  7150K .......... .......... .......... .......... .......... 11%  149M 40s
  7200K .......... .......... .......... .......... .......... 11%  120M 39s
  7250K .......... .......... .......... .......... .......... 11%  148M 39s
  7300K .......... .......... .......... .......... .......... 11%  150M 39s
  7350K .......... .......... .......... .......... .......... 11%  119M 39s
  7400K .......... .......... .......... .......... .......... 11%  152M 38s
  7450K .......... .......... .......... .......... .......... 11%  127M 38s
  7500K .......... .......... .......... .......... .......... 11%  244K 39s
  7550K .......... .......... .......... .......... .......... 11% 9.15M 39s
  7600K .......... .......... .......... .......... .......... 11% 18.8M 39s
  7650K .......... .......... .......... .......... .......... 11% 26.0M 38s
  7700K .......... .......... .......... .......... .......... 11% 10.4M 38s
  7750K .......... .......... .......... .......... .......... 11% 23.9M 38s
  7800K .......... .......... .......... .......... .......... 12%  177K 40s
  7850K .......... .......... .......... .......... .......... 12% 11.8M 39s
  7900K .......... .......... .......... .......... .......... 12% 16.8M 39s
  7950K .......... .......... .......... .......... .......... 12% 30.0M 39s
  8000K .......... .......... .......... .......... .......... 12% 85.4K 43s
  8050K .......... .......... .......... .......... .......... 12% 74.3M 43s
  8100K .......... .......... .......... .......... .......... 12% 97.6M 42s
  8150K .......... .......... .......... .......... .......... 12%  145M 42s
  8200K .......... .......... .......... .......... .......... 12%  118M 42s
  8250K .......... .......... .......... .......... .......... 12%  145M 41s
  8300K .......... .......... .......... .......... .......... 12%  126M 41s
  8350K .......... .......... .......... .......... .......... 12%  128M 41s
  8400K .......... .......... .......... .......... .......... 12% 89.9M 41s
  8450K .......... .......... .......... .......... .......... 13% 94.2M 40s
  8500K .......... .......... .......... .......... .......... 13%  109M 40s
  8550K .......... .......... .......... .......... .......... 13% 11.3M 40s
  8600K .......... .......... .......... .......... .......... 13% 11.8M 40s
  8650K .......... .......... .......... .......... .......... 13% 20.1M 39s
  8700K .......... .......... .......... .......... .......... 13%  770K 39s
  8750K .......... .......... .......... .......... .......... 13%  227K 41s
  8800K .......... .......... .......... .......... .......... 13%  129K 43s
  8850K .......... .......... .......... .......... .......... 13%  238K 44s
  8900K .......... .......... .......... .......... .......... 13% 7.24M 44s
  8950K .......... .......... .......... .......... .......... 13% 70.8M 43s
  9000K .......... .......... .......... .......... .......... 13%  131M 43s
  9050K .......... .......... .......... .......... .......... 13%  750K 43s
  9100K .......... .......... .......... .......... .......... 14% 3.58M 43s
  9150K .......... .......... .......... .......... .......... 14%  147M 43s
  9200K .......... .......... .......... .......... .......... 14%  131M 42s
  9250K .......... .......... .......... .......... .......... 14% 57.0K 47s
  9300K .......... .......... .......... .......... .......... 14%  133M 47s
  9350K .......... .......... .......... .......... .......... 14%  131M 47s
  9400K .......... .......... .......... .......... .......... 14%  147M 47s
  9450K .......... .......... .......... .......... .......... 14%  127M 46s
  9500K .......... .......... .......... .......... .......... 14%  146M 46s
  9550K .......... .......... .......... .......... .......... 14%  153M 46s
  9600K .......... .......... .......... .......... .......... 14%  162K 47s
  9650K .......... .......... .......... .......... .......... 14%  123M 47s
  9700K .......... .......... .......... .......... .......... 14%  119M 47s
  9750K .......... .......... .......... .......... .......... 15%  228K 48s
  9800K .......... .......... .......... .......... .......... 15%  652K 48s
  9850K .......... .......... .......... .......... .......... 15%  224K 49s
  9900K .......... .......... .......... .......... .......... 15% 86.3K 52s
  9950K .......... .......... .......... .......... .......... 15%  117M 51s
 10000K .......... .......... .......... .......... .......... 15% 7.36M 51s
 10050K .......... .......... .......... .......... .......... 15%  586K 51s
 10100K .......... .......... .......... .......... .......... 15%  170K 53s
 10150K .......... .......... .......... .......... .......... 15%  227K 53s
 10200K .......... .......... .......... .......... .......... 15%  176K 55s
 10250K .......... .......... .......... .......... .......... 15%  556K 55s
 10300K .......... .......... .......... .......... .......... 15%  230K 56s
 10350K .......... .......... .......... .......... .......... 15%  309K 56s
 10400K .......... .......... .......... .......... .......... 16%  356K 57s
 10450K .......... .......... .......... .......... .......... 16%  174K 58s
 10500K .......... .......... .......... .......... .......... 16%  596K 58s
 10550K .......... .......... .......... .......... .......... 16%  228K 59s
 10600K .......... .......... .......... .......... .......... 16%  312K 59s
 10650K .......... .......... .......... .......... .......... 16%  245K 60s
 10700K .......... .......... .......... .......... .......... 16% 83.1K 63s
 10750K .......... .......... .......... .......... .......... 16%  106M 62s
 10800K .......... .......... .......... .......... .......... 16%  146M 62s
 10850K .......... .......... .......... .......... .......... 16%  173K 63s
 10900K .......... .......... .......... .......... .......... 16%  213K 64s
 10950K .......... .......... .......... .......... .......... 16%  170K 65s
 11000K .......... .......... .......... .......... .......... 16%  650K 65s
 11050K .......... .......... .......... .......... .......... 17%  174K 66s
 11100K .......... .......... .......... .......... .......... 17%  212K 67s
 11150K .......... .......... .......... .......... .......... 17%  312K 67s
 11200K .......... .......... .......... .......... .......... 17%  252K 68s
 11250K .......... .......... .......... .......... .......... 17%  218K 69s
 11300K .......... .......... .......... .......... .......... 17%  665K 69s
 11350K .......... .......... .......... .......... .......... 17%  217K 69s
 11400K .......... .......... .......... .......... .......... 17% 76.3K 72s
 11450K .......... .......... .......... .......... .......... 17% 80.4M 72s
 11500K .......... .......... .......... .......... .......... 17%  156M 71s
 11550K .......... .......... .......... .......... .......... 17%  213K 72s
 11600K .......... .......... .......... .......... .......... 17%  169K 73s
 11650K .......... .......... .......... .......... .......... 17%  306K 73s
 11700K .......... .......... .......... .......... .......... 18%  245K 74s
 11750K .......... .......... .......... .......... .......... 18%  214K 74s
 11800K .......... .......... .......... .......... .......... 18%  318K 75s
 11850K .......... .......... .......... .......... .......... 18% 84.2K 77s
 11900K .......... .......... .......... .......... .......... 18%  408K 77s
 11950K .......... .......... .......... .......... .......... 18%  661K 77s
 12000K .......... .......... .......... .......... .......... 18%  210K 78s
 12050K .......... .......... .......... .......... .......... 18%  173K 79s
 12100K .......... .......... .......... .......... .......... 18%  171K 80s
 12150K .......... .......... .......... .......... .......... 18%  309K 80s
 12200K .......... .......... .......... .......... .......... 18%  236K 80s
 12250K .......... .......... .......... .......... .......... 18%  168K 81s
 12300K .......... .......... .......... .......... .......... 18%  127K 83s
 12350K .......... .......... .......... .......... .......... 19%  368K 83s
 12400K .......... .......... .......... .......... .......... 19%  171K 84s
 12450K .......... .......... .......... .......... .......... 19%  109K 85s
 12500K .......... .......... .......... .......... .......... 19%  224K 86s
 12550K .......... .......... .......... .......... .......... 19%  135K 87s

Mu et al., 2025取的区域是: 基因起始位置(非狭义的TSS)上游5kb, 下游2kb

In [ ]:
%%bash

awk '$0 !~ /^#/ && $3=="gene"' "./gtf/Apis_mellifera.gtf" > "./gtf/Apis_mellifera_genes.gtf" # 仅保留类型为gene的行, 且去掉注释行
bedtools sort -i "./gtf/Apis_mellifera_genes.gtf" > "./gtf/Apis_mellifera_genes_sorted.gtf" # 排序

In [ ]:
%%bash
#! 根据HY以往的操作记录(.subproject/01_choose_gene_in_cistarget/01_choose_gene_in_cistarget.py)和asertlab提供的feather，还需要去掉全部线粒体基因，使用剩余基因建库
# CM009947.2 是线粒体对应的染色体名称
awk '$1 != "CM009947.2"' "./gtf/Apis_mellifera_genes_sorted.gtf" > "./gtf/Apis_mellifera_genes_sorted_nomt.gtf"

In [ ]:
%%bash

wc -l "./gtf/Apis_mellifera_genes_sorted.gtf"
wc -l "./gtf/Apis_mellifera_genes_sorted_nomt.gtf"
# 37个基因，未出错

12398 ./gtf/Apis_mellifera_genes_sorted.gtf
12361 ./gtf/Apis_mellifera_genes_sorted_nomt.gtf

# 开始提取上游5kb和下游2kb

### 读取GTF

In [26]:
import pyranges as pr

am_gtf = pr.read_gtf("./gtf/Apis_mellifera_genes_sorted_nomt.gtf").df
am_gtf

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,gene_source,gene_biotype,gene_name
0,CM009931.2,RefSeq,gene,10791,17180,.,+,.,LOC551555,RefSeq,protein_coding,NaN
1,CM009931.2,RefSeq,gene,23612,26208,.,+,.,GeneID_409940,RefSeq,protein_coding,Rfwd3
2,CM009931.2,RefSeq,gene,29939,39215,.,+,.,LOC551448,RefSeq,protein_coding,NaN
3,CM009931.2,RefSeq,gene,42764,45255,.,+,.,LOC408567,RefSeq,protein_coding,NaN
4,CM009931.2,RefSeq,gene,45527,79393,.,+,.,LOC107964061,RefSeq,protein_coding,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12356,QIUM02000210.1,RefSeq,gene,457,3977,.,-,.,LOC113219357,RefSeq,pseudogene,NaN
12357,QIUM02000210.1,RefSeq,gene,5407,5560,.,-,.,LOC113219356,RefSeq,rRNA,NaN
12358,QIUM02000211.1,RefSeq,gene,0,3962,.,+,.,LOC113219387,RefSeq,rRNA,NaN
12359,QIUM02000217.1,RefSeq,gene,556,1523,.,-,.,LOC113219358,RefSeq,protein_coding,NaN
12360,QIUM02000219.1,RefSeq,gene,2141,4064,.,+,.,LOC113219341,RefSeq,rRNA,NaN

### 添加各染色体长度(防止下游2kb超过染色体长度)

In [6]:
%%bash

wget -O "./fasta/Apis_mellifera.fai" "https://ftp.ensemblgenomes.ebi.ac.uk/pub/metazoa/current/fasta/apis_mellifera/dna_index/Apis_mellifera.Amel_HAv3.1.dna.toplevel.fa.gz.fai"

--2026-08-14 21:26:02--  https://ftp.ensemblgenomes.ebi.ac.uk/pub/metazoa/current/fasta/apis_mellifera/dna_index/Apis_mellifera.Amel_HAv3.1.dna.toplevel.fa.gz.fai

Resolving ftp.ensemblgenomes.ebi.ac.uk (ftp.ensemblgenomes.ebi.ac.uk)... 193.62.193.161
Connecting to ftp.ensemblgenomes.ebi.ac.uk (ftp.ensemblgenomes.ebi.ac.uk)|193.62.193.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6155 (6.0K) [application/x-gzip]
Saving to: './fasta/Apis_mellifera.fai'

     0K ......                                                100%  649M=0s

2026-08-14 21:26:04 (649 MB/s) - './fasta/Apis_mellifera.fai' saved [6155/6155]

In [13]:
import pandas as pd

am_genome_length = pd.read_csv("./fasta/Apis_mellifera.fai", header=None, sep="\t")[[0, 1]].set_index(0)[1]
am_genome_length

0
QIUM02000069.1      486754
QIUM02000070.1      311923
QIUM02000071.1      135562
QIUM02000072.1      120686
QIUM02000073.1      108711
                    ...
CM009943.2        11279722
CM009944.2        10670842
CM009945.2         9534514
CM009946.2         7238532
CM009947.2           16343
Name: 1, Length: 177, dtype: int64

In [27]:
am_gtf["chrom_length"] = am_gtf["Chromosome"].map(am_genome_length)
am_gtf

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,gene_source,gene_biotype,gene_name,chrom_length
0,CM009931.2,RefSeq,gene,10791,17180,.,+,.,LOC551555,RefSeq,protein_coding,NaN,27754200
1,CM009931.2,RefSeq,gene,23612,26208,.,+,.,GeneID_409940,RefSeq,protein_coding,Rfwd3,27754200
2,CM009931.2,RefSeq,gene,29939,39215,.,+,.,LOC551448,RefSeq,protein_coding,NaN,27754200
3,CM009931.2,RefSeq,gene,42764,45255,.,+,.,LOC408567,RefSeq,protein_coding,NaN,27754200
4,CM009931.2,RefSeq,gene,45527,79393,.,+,.,LOC107964061,RefSeq,protein_coding,NaN,27754200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12356,QIUM02000210.1,RefSeq,gene,457,3977,.,-,.,LOC113219357,RefSeq,pseudogene,NaN,5948
12357,QIUM02000210.1,RefSeq,gene,5407,5560,.,-,.,LOC113219356,RefSeq,rRNA,NaN,5948
12358,QIUM02000211.1,RefSeq,gene,0,3962,.,+,.,LOC113219387,RefSeq,rRNA,NaN,5439
12359,QIUM02000217.1,RefSeq,gene,556,1523,.,-,.,LOC113219358,RefSeq,protein_coding,NaN,4502
12360,QIUM02000219.1,RefSeq,gene,2141,4064,.,+,.,LOC113219341,RefSeq,rRNA,NaN,4248

In [33]:
sum(am_gtf["chrom_length"].isna()) # 追加无误，继续

0

In [29]:
import numpy as np

plus = am_gtf["Strand"] == "+"

am_gtf["Neo_Start"] = np.where(plus, am_gtf["Start"] - 5000, am_gtf["End"] - 2001)
am_gtf["Neo_End"]   = np.where(plus, am_gtf["Start"] + 2001, am_gtf["End"] + 5000)
am_gtf

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,gene_source,gene_biotype,gene_name,chrom_length,Neo_Start,Neo_End
0,CM009931.2,RefSeq,gene,10791,17180,.,+,.,LOC551555,RefSeq,protein_coding,NaN,27754200,5791,12792
1,CM009931.2,RefSeq,gene,23612,26208,.,+,.,GeneID_409940,RefSeq,protein_coding,Rfwd3,27754200,18612,25613
2,CM009931.2,RefSeq,gene,29939,39215,.,+,.,LOC551448,RefSeq,protein_coding,NaN,27754200,24939,31940
3,CM009931.2,RefSeq,gene,42764,45255,.,+,.,LOC408567,RefSeq,protein_coding,NaN,27754200,37764,44765
4,CM009931.2,RefSeq,gene,45527,79393,.,+,.,LOC107964061,RefSeq,protein_coding,NaN,27754200,40527,47528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12356,QIUM02000210.1,RefSeq,gene,457,3977,.,-,.,LOC113219357,RefSeq,pseudogene,NaN,5948,1976,8977
12357,QIUM02000210.1,RefSeq,gene,5407,5560,.,-,.,LOC113219356,RefSeq,rRNA,NaN,5948,3559,10560
12358,QIUM02000211.1,RefSeq,gene,0,3962,.,+,.,LOC113219387,RefSeq,rRNA,NaN,5439,-5000,2001
12359,QIUM02000217.1,RefSeq,gene,556,1523,.,-,.,LOC113219358,RefSeq,protein_coding,NaN,4502,-478,6523
12360,QIUM02000219.1,RefSeq,gene,2141,4064,.,+,.,LOC113219341,RefSeq,rRNA,NaN,4248,-2859,4142

#### 如果Neo_Start为负数，将其变成0，如果Neo_End超出了同行chrom_length，将其替换为chrom_length

In [30]:
am_gtf["Neo_Start"] = am_gtf["Neo_Start"].clip(lower=0)
am_gtf["Neo_End"] = am_gtf[["Neo_End", "chrom_length"]].min(axis=1)
am_gtf

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,gene_source,gene_biotype,gene_name,chrom_length,Neo_Start,Neo_End
0,CM009931.2,RefSeq,gene,10791,17180,.,+,.,LOC551555,RefSeq,protein_coding,NaN,27754200,5791,12792
1,CM009931.2,RefSeq,gene,23612,26208,.,+,.,GeneID_409940,RefSeq,protein_coding,Rfwd3,27754200,18612,25613
2,CM009931.2,RefSeq,gene,29939,39215,.,+,.,LOC551448,RefSeq,protein_coding,NaN,27754200,24939,31940
3,CM009931.2,RefSeq,gene,42764,45255,.,+,.,LOC408567,RefSeq,protein_coding,NaN,27754200,37764,44765
4,CM009931.2,RefSeq,gene,45527,79393,.,+,.,LOC107964061,RefSeq,protein_coding,NaN,27754200,40527,47528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12356,QIUM02000210.1,RefSeq,gene,457,3977,.,-,.,LOC113219357,RefSeq,pseudogene,NaN,5948,1976,5948
12357,QIUM02000210.1,RefSeq,gene,5407,5560,.,-,.,LOC113219356,RefSeq,rRNA,NaN,5948,3559,5948
12358,QIUM02000211.1,RefSeq,gene,0,3962,.,+,.,LOC113219387,RefSeq,rRNA,NaN,5439,0,2001
12359,QIUM02000217.1,RefSeq,gene,556,1523,.,-,.,LOC113219358,RefSeq,protein_coding,NaN,4502,0,4502
12360,QIUM02000219.1,RefSeq,gene,2141,4064,.,+,.,LOC113219341,RefSeq,rRNA,NaN,4248,0,4142

### 因为需要使用bedtools getfasta -s，所以必须保留Strand列：

In [35]:
am_gtf_4_bed = am_gtf[["Chromosome", "Neo_Start", "Neo_End", "gene_id", "Score", "Strand"]]
am_gtf_4_bed

           Chromosome  Neo_Start  Neo_End        gene_id Score Strand
0          CM009931.2       5791    12792      LOC551555     .      +
1          CM009931.2      18612    25613  GeneID_409940     .      +
2          CM009931.2      24939    31940      LOC551448     .      +
3          CM009931.2      37764    44765      LOC408567     .      +
4          CM009931.2      40527    47528   LOC107964061     .      +
...               ...        ...      ...            ...   ...    ...
12356  QIUM02000210.1       1976     5948   LOC113219357     .      -
12357  QIUM02000210.1       3559     5948   LOC113219356     .      -
12358  QIUM02000211.1          0     2001   LOC113219387     .      +
12359  QIUM02000217.1          0     4502   LOC113219358     .      -
12360  QIUM02000219.1          0     4142   LOC113219341     .      +

[12361 rows x 6 columns]

In [36]:
am_gtf_4_bed.to_csv("./metadata/Amel_4_cisTarget.bed", sep="\t", index=False, header=False)

# 根据bed文件生成fasta

In [9]:
%%bash

bedtools getfasta \
    -fi "./fasta/Apis_mellifera.fasta" \
    -bed "./metadata/Amel_4_cisTarget.bed" \
    -name \
    -s \
    -fo "./fasta/Apis_mellifera_4_cisTarget.fasta"

In [ ]:
import pyfaidx

Am4cis = pyfaidx.Fasta("./fasta/Apis_mellifera_4_cisTarget.fasta")
# 检查Apis_mellifera_4_cisTarget.fasta.fai，确定长度是7001以保证bedtools没取错:

In [12]:
%%bash

head "./fasta/Apis_mellifera_4_cisTarget.fasta.fai"

LOC551555::CM009931.2:5791-12792(+)	7001	37	7001	7002
GeneID_409940::CM009931.2:18612-25613(+)	7001	7081	7001	7002
LOC551448::CM009931.2:24939-31940(+)	7001	14121	7001	7002
LOC408567::CM009931.2:37764-44765(+)	7001	21161	7001	7002
LOC107964061::CM009931.2:40527-47528(+)	7001	28204	7001	7002
LOC113219112::CM009931.2:86243-93244(+)	7001	35247	7001	7002
LOC726450::CM009931.2:86681-93682(+)	7001	42287	7001	7002
LOC408565::CM009931.2:112007-119008(+)	7001	49329	7001	7002
LOC113219398::CM009931.2:121476-128477(+)	7001	56374	7001	7002
GeneID_104796173::CM009931.2:134121-141122(+)	7001	63423	7001	7002

# 获取cBust，即将开始构建cisTarget数据库

In [ ]:
%%bash

cd ~/.local/bin
wget https://resources.aertslab.org/cistarget/programs/cbust
chmod +x cbust