使用create_cistarget_motif_databases.py构建cisTarget数据库前的准备工作： 生成create_cistarget_motif_databases.py -f参数对应的fasta文件

In [1]:
%%bash

mkdir -p "./fasta"
wget -O "./fasta/Apis_cerana.fasta.gz" "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/029/169/275/GCF_029169275.2_AcerK_1.0/GCF_029169275.2_AcerK_1.0_genomic.fna.gz"
gunzip "./fasta/Apis_cerana.fasta.gz"

--2026-09-04 16:37:35--  https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/029/169/275/GCF_029169275.2_AcerK_1.0/GCF_029169275.2_AcerK_1.0_genomic.fna.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 2607:f220:41e:250::12, 2607:f220:41e:250::11, 130.14.250.7, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|2607:f220:41e:250::12|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 69251800 (66M) [application/x-gzip]
Saving to: './fasta/Apis_cerana.fasta.gz'

     0K .......... .......... .......... .......... ..........  0%  245K 4m36s
    50K .......... .......... .......... .......... ..........  0%  243K 4m37s
   100K .......... .......... .......... .......... ..........  0%  246K 4m36s
   150K .......... .......... .......... .......... ..........  0% 36.9M 3m27s
   200K .......... .......... .......... .......... ..........  0% 24.3M 2m46s
   250K .......... .......... .......... .......... ..........  0% 33.7M 2m19s
   300K .......... .......... .......... .......... ..........  0%  250K 2m37s
   350K .......... .......... .......... .......... ..........  0% 23.2M 2m18s
   400K .......... .......... .......... .......... ..........  0% 28.0M 2m3s
   450K .......... .......... .......... .......... ..........  0% 23.8M 1m51s
   500K .......... .......... .......... .......... ..........  0% 24.6M 1m41s
   550K .......... .......... .......... .......... ..........  0% 26.1M 92s
   600K .......... .......... .......... .......... ..........  0%  259K 1m45s
   650K .......... .......... .......... .......... ..........  1% 47.5M 98s
   700K .......... .......... .......... .......... ..........  1% 22.0M 91s
   750K .......... .......... .......... .......... ..........  1% 41.5M 86s
   800K .......... .......... .......... .......... ..........  1%  124K 1m52s
   850K .......... .......... .......... .......... ..........  1% 35.7M 1m46s
   900K .......... .......... .......... .......... ..........  1% 70.6M 1m40s
   950K .......... .......... .......... .......... ..........  1% 99.9M 95s
  1000K .......... .......... .......... .......... ..........  1%  118M 91s
  1050K .......... .......... .......... .......... ..........  1%  118M 87s
  1100K .......... .......... .......... .......... ..........  1%  104M 83s
  1150K .......... .......... .......... .......... ..........  1%  118M 79s
  1200K .......... .......... .......... .......... ..........  1%  102M 76s
  1250K .......... .......... .......... .......... ..........  1%  117M 73s
  1300K .......... .......... .......... .......... ..........  1%  117M 70s
  1350K .......... .......... .......... .......... ..........  2%  856K 71s
  1400K .......... .......... .......... .......... ..........  2% 74.9M 68s
  1450K .......... .......... .......... .......... ..........  2%  101M 66s
  1500K .......... .......... .......... .......... ..........  2%  105M 64s
  1550K .......... .......... .......... .......... ..........  2%  119M 62s
  1600K .......... .......... .......... .......... ..........  2% 99.4M 60s
  1650K .......... .......... .......... .......... ..........  2%  118M 58s
  1700K .......... .......... .......... .......... ..........  2%  107M 56s
  1750K .......... .......... .......... .......... ..........  2%  123M 55s
  1800K .......... .......... .......... .......... ..........  2%  130M 53s
  1850K .......... .......... .......... .......... ..........  2%  110M 52s
  1900K .......... .......... .......... .......... ..........  2%  125M 50s
  1950K .......... .......... .......... .......... ..........  2%  107M 49s
  2000K .......... .......... .......... .......... ..........  3%  125M 48s
  2050K .......... .......... .......... .......... ..........  3%  252K 53s
  2100K .......... .......... .......... .......... ..........  3% 29.0M 52s
  2150K .......... .......... .......... .......... ..........  3% 43.9M 51s
  2200K .......... .......... .......... .......... ..........  3% 36.5M 49s
  2250K .......... .......... .......... .......... ..........  3% 33.6M 48s
  2300K .......... .......... .......... .......... ..........  3% 40.3M 47s
  2350K .......... .......... .......... .......... ..........  3% 57.5M 46s
  2400K .......... .......... .......... .......... ..........  3% 49.9M 45s
  2450K .......... .......... .......... .......... ..........  3% 23.5M 44s
  2500K .......... .......... .......... .......... ..........  3% 79.0M 44s
  2550K .......... .......... .......... .......... ..........  3% 72.7M 43s
  2600K .......... .......... .......... .......... ..........  3% 55.9M 42s
  2650K .......... .......... .......... .......... ..........  3% 69.8M 41s
  2700K .......... .......... .......... .......... ..........  4%  127K 50s
  2750K .......... .......... .......... .......... ..........  4% 58.2M 49s
  2800K .......... .......... .......... .......... ..........  4% 78.3M 48s
  2850K .......... .......... .......... .......... ..........  4% 68.6M 47s
  2900K .......... .......... .......... .......... ..........  4% 62.8M 46s
  2950K .......... .......... .......... .......... ..........  4% 61.2M 45s
  3000K .......... .......... .......... .......... ..........  4% 49.0M 45s
  3050K .......... .......... .......... .......... ..........  4% 59.9M 44s
  3100K .......... .......... .......... .......... ..........  4% 68.8M 43s
  3150K .......... .......... .......... .......... ..........  4% 58.5M 43s
  3200K .......... .......... .......... .......... ..........  4% 48.5M 42s
  3250K .......... .......... .......... .......... ..........  4% 42.9M 41s
  3300K .......... .......... .......... .......... ..........  4% 65.1M 41s
  3350K .......... .......... .......... .......... ..........  5% 64.4M 40s
  3400K .......... .......... .......... .......... ..........  5% 87.1M 39s
  3450K .......... .......... .......... .......... ..........  5% 47.6M 39s
  3500K .......... .......... .......... .......... ..........  5% 47.7M 38s
  3550K .......... .......... .......... .......... ..........  5% 67.2M 38s
  3600K .......... .......... .......... .......... ..........  5% 55.5M 37s
  3650K .......... .......... .......... .......... ..........  5% 86.0M 37s
  3700K .......... .......... .......... .......... ..........  5% 66.6M 36s
  3750K .......... .......... .......... .......... ..........  5% 55.7M 36s
  3800K .......... .......... .......... .......... ..........  5% 81.3M 35s
  3850K .......... .......... .......... .......... ..........  5%  102M 35s
  3900K .......... .......... .......... .......... ..........  5%  118M 34s
  3950K .......... .......... .......... .......... ..........  5%  105M 34s
  4000K .......... .......... .......... .......... ..........  5%  114M 33s
  4050K .......... .......... .......... .......... ..........  6%  113M 33s
  4100K .......... .......... .......... .......... ..........  6%  105M 33s
  4150K .......... .......... .......... .......... ..........  6%  120M 32s
  4200K .......... .......... .......... .......... ..........  6%  105M 32s
  4250K .......... .......... .......... .......... ..........  6%  117M 31s
  4300K .......... .......... .......... .......... ..........  6%  120M 31s
  4350K .......... .......... .......... .......... ..........  6% 1.04M 31s
  4400K .......... .......... .......... .......... ..........  6%  367K 33s
  4450K .......... .......... .......... .......... ..........  6% 17.7M 32s
  4500K .......... .......... .......... .......... ..........  6% 20.2M 32s
  4550K .......... .......... .......... .......... ..........  6% 21.4M 32s
  4600K .......... .......... .......... .......... ..........  6% 22.0M 31s
  4650K .......... .......... .......... .......... ..........  6% 24.4M 31s
  4700K .......... .......... .......... .......... ..........  7% 22.4M 31s
  4750K .......... .......... .......... .......... ..........  7% 25.0M 30s
  4800K .......... .......... .......... .......... ..........  7% 19.9M 30s
  4850K .......... .......... .......... .......... ..........  7% 19.0M 30s
  4900K .......... .......... .......... .......... ..........  7% 26.4M 30s
  4950K .......... .......... .......... .......... ..........  7% 1.09M 30s
  5000K .......... .......... .......... .......... ..........  7%  357K 31s
  5050K .......... .......... .......... .......... ..........  7% 12.7M 31s
  5100K .......... .......... .......... .......... ..........  7% 16.4M 31s
  5150K .......... .......... .......... .......... ..........  7% 20.8M 30s
  5200K .......... .......... .......... .......... ..........  7% 16.7M 30s
  5250K .......... .......... .......... .......... ..........  7% 22.3M 30s
  5300K .......... .......... .......... .......... ..........  7% 38.9M 29s
  5350K .......... .......... .......... .......... ..........  7% 16.9M 29s
  5400K .......... .......... .......... .......... ..........  8% 41.6M 29s
  5450K .......... .......... .......... .......... ..........  8% 21.8M 29s
  5500K .......... .......... .......... .......... ..........  8% 38.1M 28s
  5550K .......... .......... .......... .......... ..........  8% 22.0M 28s
  5600K .......... .......... .......... .......... ..........  8% 1.24M 28s
  5650K .......... .......... .......... .......... ..........  8%  355K 30s
  5700K .......... .......... .......... .......... ..........  8% 13.0M 29s
  5750K .......... .......... .......... .......... ..........  8% 20.0M 29s
  5800K .......... .......... .......... .......... ..........  8% 22.9M 29s
  5850K .......... .......... .......... .......... ..........  8% 18.7M 29s
  5900K .......... .......... .......... .......... ..........  8% 21.6M 28s
  5950K .......... .......... .......... .......... ..........  8% 19.0M 28s
  6000K .......... .......... .......... .......... ..........  8% 21.5M 28s
  6050K .......... .......... .......... .......... ..........  9% 24.4M 28s
  6100K .......... .......... .......... .......... ..........  9% 18.5M 27s
  6150K .......... .......... .......... .......... ..........  9% 21.1M 27s
  6200K .......... .......... .......... .......... ..........  9% 24.3M 27s
  6250K .......... .......... .......... .......... ..........  9% 1.35M 27s
  6300K .......... .......... .......... .......... ..........  9%  355K 28s
  6350K .......... .......... .......... .......... ..........  9% 14.7M 28s
  6400K .......... .......... .......... .......... ..........  9% 16.3M 28s
  6450K .......... .......... .......... .......... ..........  9% 25.8M 28s
  6500K .......... .......... .......... .......... ..........  9% 19.4M 27s
  6550K .......... .......... .......... .......... ..........  9% 19.7M 27s
  6600K .......... .......... .......... .......... ..........  9% 22.6M 27s
  6650K .......... .......... .......... .......... ..........  9% 21.7M 27s
  6700K .......... .......... .......... .......... ..........  9% 19.7M 27s
  6750K .......... .......... .......... .......... .......... 10% 21.4M 26s
  6800K .......... .......... .......... .......... .......... 10% 23.4M 26s
  6850K .......... .......... .......... .......... .......... 10% 22.7M 26s
  6900K .......... .......... .......... .......... .......... 10% 1.36M 26s
  6950K .......... .......... .......... .......... .......... 10%  354K 27s
  7000K .......... .......... .......... .......... .......... 10% 16.2M 27s
  7050K .......... .......... .......... .......... .......... 10% 17.5M 27s
  7100K .......... .......... .......... .......... .......... 10% 23.6M 27s
  7150K .......... .......... .......... .......... .......... 10% 20.4M 26s
  7200K .......... .......... .......... .......... .......... 10% 16.9M 26s
  7250K .......... .......... .......... .......... .......... 10% 27.8M 26s
  7300K .......... .......... .......... .......... .......... 10% 23.2M 26s
  7350K .......... .......... .......... .......... .......... 10% 17.8M 26s
  7400K .......... .......... .......... .......... .......... 11% 22.5M 25s
  7450K .......... .......... .......... .......... .......... 11% 20.1M 25s
  7500K .......... .......... .......... .......... .......... 11% 22.3M 25s
  7550K .......... .......... .......... .......... .......... 11% 1.41M 25s
  7600K .......... .......... .......... .......... .......... 11%  354K 26s
  7650K .......... .......... .......... .......... .......... 11% 12.9M 26s
  7700K .......... .......... .......... .......... .......... 11% 17.2M 26s
  7750K .......... .......... .......... .......... .......... 11% 23.1M 26s
  7800K .......... .......... .......... .......... .......... 11% 18.6M 25s
  7850K .......... .......... .......... .......... .......... 11% 25.2M 25s
  7900K .......... .......... .......... .......... .......... 11% 18.1M 25s
  7950K .......... .......... .......... .......... .......... 11% 28.9M 25s
  8000K .......... .......... .......... .......... .......... 11% 23.5M 25s
  8050K .......... .......... .......... .......... .......... 11% 18.8M 25s
  8100K .......... .......... .......... .......... .......... 12% 19.9M 25s
  8150K .......... .......... .......... .......... .......... 12% 24.1M 24s
  8200K .......... .......... .......... .......... .......... 12% 17.8M 24s
  8250K .......... .......... .......... .......... .......... 12% 1.38M 24s
  8300K .......... .......... .......... .......... .......... 12%  357K 25s
  8350K .......... .......... .......... .......... .......... 12% 13.4M 25s
  8400K .......... .......... .......... .......... .......... 12% 15.8M 25s
  8450K .......... .......... .......... .......... .......... 12% 28.8M 25s
  8500K .......... .......... .......... .......... .......... 12% 18.0M 25s
  8550K .......... .......... .......... .......... .......... 12% 28.9M 24s
  8600K .......... .......... .......... .......... .......... 12% 20.5M 24s
  8650K .......... .......... .......... .......... .......... 12% 23.3M 24s
  8700K .......... .......... .......... .......... .......... 12% 20.3M 24s
  8750K .......... .......... .......... .......... .......... 13% 18.1M 24s
  8800K .......... .......... .......... .......... .......... 13% 19.4M 24s
  8850K .......... .......... .......... .......... .......... 13% 24.2M 24s
  8900K .......... .......... .......... .......... .......... 13% 1.43M 24s
  8950K .......... .......... .......... .......... .......... 13%  355K 24s
  9000K .......... .......... .......... .......... .......... 13% 13.2M 24s
  9050K .......... .......... .......... .......... .......... 13% 18.7M 24s
  9100K .......... .......... .......... .......... .......... 13% 13.2M 24s
  9150K .......... .......... .......... .......... .......... 13%  192K 25s
  9200K .......... .......... .......... .......... .......... 13% 73.4M 25s
  9250K .......... .......... .......... .......... .......... 13% 92.7M 25s
  9300K .......... .......... .......... .......... .......... 13%  107M 25s
  9350K .......... .......... .......... .......... .......... 13% 95.1M 25s
  9400K .......... .......... .......... .......... .......... 13%  107M 25s
  9450K .......... .......... .......... .......... .......... 14% 95.4M 25s
  9500K .......... .......... .......... .......... .......... 14%  110M 24s
  9550K .......... .......... .......... .......... .......... 14%  111M 24s
  9600K .......... .......... .......... .......... .......... 14% 92.7M 24s
  9650K .......... .......... .......... .......... .......... 14%  111M 24s
  9700K .......... .......... .......... .......... .......... 14% 95.7M 24s
  9750K .......... .......... .......... .......... .......... 14%  108M 24s
  9800K .......... .......... .......... .......... .......... 14%  111M 24s
  9850K .......... .......... .......... .......... .......... 14% 93.5M 23s
  9900K .......... .......... .......... .......... .......... 14%  111M 23s
  9950K .......... .......... .......... .......... .......... 14% 92.6M 23s
 10000K .......... .......... .......... .......... .......... 14%  114M 23s
 10050K .......... .......... .......... .......... .......... 14%  115M 23s
 10100K .......... .......... .......... .......... .......... 15%  105M 23s
 10150K .......... .......... .......... .......... .......... 15%  119M 23s
 10200K .......... .......... .......... .......... .......... 15%  102M 23s
 10250K .......... .......... .......... .......... .......... 15%  121M 22s
 10300K .......... .......... .......... .......... .......... 15%  386K 23s
 10350K .......... .......... .......... .......... .......... 15% 11.1M 23s
 10400K .......... .......... .......... .......... .......... 15% 11.0M 23s
 10450K .......... .......... .......... .......... .......... 15% 14.6M 23s
 10500K .......... .......... .......... .......... .......... 15% 13.7M 23s
 10550K .......... .......... .......... .......... .......... 15% 16.3M 22s
 10600K .......... .......... .......... .......... .......... 15% 15.1M 22s
 10650K .......... .......... .......... .......... .......... 15% 2.77M 22s
 10700K .......... .......... .......... .......... .......... 15% 11.3M 22s
 10750K .......... .......... .......... .......... .......... 15% 2.12M 22s
 10800K .......... .......... .......... .......... .......... 16%  358K 23s
 10850K .......... .......... .......... .......... .......... 16% 12.8M 23s
 10900K .......... .......... .......... .......... .......... 16% 14.0M 23s
 10950K .......... .......... .......... .......... .......... 16% 17.4M 22s
 11000K .......... .......... .......... .......... .......... 16% 15.3M 22s
 11050K .......... .......... .......... .......... .......... 16% 16.8M 22s
 11100K .......... .......... .......... .......... .......... 16% 14.1M 22s
 11150K .......... .......... .......... .......... .......... 16% 2.68M 22s
 11200K .......... .......... .......... .......... .......... 16% 13.0M 22s
 11250K .......... .......... .......... .......... .......... 16% 2.14M 22s
 11300K .......... .......... .......... .......... .......... 16%  359K 23s
 11350K .......... .......... .......... .......... .......... 16% 12.4M 23s
 11400K .......... .......... .......... .......... .......... 16% 14.5M 22s
 11450K .......... .......... .......... .......... .......... 17% 21.2M 22s
 11500K .......... .......... .......... .......... .......... 17% 16.2M 22s
 11550K .......... .......... .......... .......... .......... 17% 14.8M 22s
 11600K .......... .......... .......... .......... .......... 17% 14.0M 22s
 11650K .......... .......... .......... .......... .......... 17% 14.9M 22s
 11700K .......... .......... .......... .......... .......... 17% 2.58M 22s
 11750K .......... .......... .......... .......... .......... 17% 2.49M 22s
 11800K .......... .......... .......... .......... .......... 17%  351K 22s
 11850K .......... .......... .......... .......... .......... 17% 11.7M 22s
 11900K .......... .......... .......... .......... .......... 17% 23.2M 22s
 11950K .......... .......... .......... .......... .......... 17% 19.7M 22s
 12000K .......... .......... .......... .......... .......... 17% 14.6M 22s
 12050K .......... .......... .......... .......... .......... 17% 19.0M 22s
 12100K .......... .......... .......... .......... .......... 17% 12.5M 22s
 12150K .......... .......... .......... .......... .......... 18% 17.3M 22s
 12200K .......... .......... .......... .......... .......... 18% 2.68M 22s
 12250K .......... .......... .......... .......... .......... 18% 2.56M 22s
 12300K .......... .......... .......... .......... .......... 18%  349K 22s
 12350K .......... .......... .......... .......... .......... 18% 10.6M 22s
 12400K .......... .......... .......... .......... .......... 18% 18.7M 22s
 12450K .......... .......... .......... .......... .......... 18% 14.7M 22s
 12500K .......... .......... .......... .......... .......... 18% 23.7M 22s
 12550K .......... .......... .......... .......... .......... 18% 20.0M 22s

Mu et al., 2025取的区域是: 基因起始位置(非狭义的TSS)上游5kb, 下游2kb

In [2]:
%%bash

awk '$0 !~ /^#/ && $3=="gene"' "./gtf/Apis_cerana.gtf" > "./gtf/Apis_cerana_genes.gtf" # 仅保留类型为gene的行, 且去掉注释行
bedtools sort -i "./gtf/Apis_cerana_genes.gtf" > "./gtf/Apis_cerana_genes_sorted.gtf" # 排序

In [ ]:
%%bash
#! 根据HY以往的操作记录(.subproject/01_choose_gene_in_cistarget/01_choose_gene_in_cistarget.py)和asertlab提供的feather，还需要去掉全部线粒体基因，使用剩余基因建库
# NC_014295.1 是线粒体对应的染色体名称
awk '$1 != "NC_014295.1"' "./gtf/Apis_cerana_genes_sorted.gtf" > "./gtf/Apis_cerana_genes_sorted_nomt.gtf"

In [6]:
%%bash

wc -l "./gtf/Apis_cerana_genes_sorted.gtf"
wc -l "./gtf/Apis_cerana_genes_sorted_nomt.gtf"
# 37个基因，未出错

12561 ./gtf/Apis_cerana_genes_sorted.gtf
12548 ./gtf/Apis_cerana_genes_sorted_nomt.gtf

# 开始提取上游5kb和下游2kb

### 读取GTF

In [10]:
import pyranges as pr

ac_gtf = pr.read_gtf("./gtf/Apis_cerana_genes_sorted_nomt.gtf").df
ac_gtf

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,db_xref,description,gbkey,gene,gene_biotype,gene_synonym,partial
0,NC_083852.1,Gnomon,gene,19209,25539,.,+,.,LOC107992805,GeneID:107992805,MATH and LRR domain-containing protein PFE0570w,Gene,LOC107992805,protein_coding,NaN,NaN
1,NC_083852.1,Gnomon,gene,31867,34512,.,+,.,LOC107992868,GeneID:107992868,E3 ubiquitin-protein ligase RFWD3,Gene,LOC107992868,protein_coding,NaN,NaN
2,NC_083852.1,Gnomon,gene,38244,46847,.,+,.,LOC107992788,GeneID:107992788,ribose-phosphate pyrophosphokinase 1,Gene,LOC107992788,protein_coding,NaN,NaN
3,NC_083852.1,Gnomon,gene,50438,53323,.,+,.,LOC133667054,GeneID:133667054,"medium-chain specific acyl-CoA dehydrogenase, ...",Gene,LOC133667054,protein_coding,NaN,NaN
4,NC_083852.1,Gnomon,gene,53446,115364,.,+,.,LOC107992756,GeneID:107992756,nuclear hormone receptor FTZ-F1,Gene,LOC107992756,protein_coding,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12543,NW_026893559.1,Gnomon,gene,230125,230503,.,+,.,LOC133667677,GeneID:133667677,uncharacterized LOC133667677,Gene,LOC133667677,protein_coding,NaN,NaN
12544,NW_026893559.1,Gnomon,gene,52880,62536,.,-,.,LOC133667674,GeneID:133667674,uncharacterized LOC133667674,Gene,LOC133667674,protein_coding,NaN,NaN
12545,NW_026893559.1,Gnomon,gene,233705,238437,.,-,.,LOC133667678,GeneID:133667678,uncharacterized LOC133667678,Gene,LOC133667678,protein_coding,NaN,NaN
12546,NW_026893559.1,Gnomon,gene,239924,242142,.,-,.,LOC133667679,GeneID:133667679,uncharacterized LOC133667679,Gene,LOC133667679,protein_coding,NaN,NaN
12547,NW_026893561.1,Gnomon,gene,31282,31660,.,+,.,LOC133667710,GeneID:133667710,uncharacterized LOC133667710,Gene,LOC133667710,protein_coding,NaN,NaN

### 添加各染色体长度(防止下游2kb超过染色体长度)

In [8]:
# 生成index
from pyfaidx import Fasta

Fasta("./fasta/Apis_cerana.fasta")

Fasta("./fasta/Apis_cerana.fasta")

In [9]:
import pandas as pd

ac_genome_length = pd.read_csv("./fasta/Apis_cerana.fasta.fai", header=None, sep="\t")[[0, 1]].set_index(0)[1]
ac_genome_length

0
NC_083852.1       27131825
NC_083853.1       15875455
NC_083854.1       13386827
NC_083855.1       13159592
NC_083856.1       13471485
NC_083857.1       17285085
NC_083858.1       13645534
NC_083859.1       12170773
NC_083860.1       11954044
NC_083861.1       12434583
NC_083862.1       15832348
NC_083863.1       11302906
NC_083864.1       11000381
NC_083865.1       11731789
NC_083866.1        9491825
NC_083867.1        7109830
NW_026893558.1     5207728
NW_026893559.1      250740
NW_026893560.1       93405
NW_026893561.1      504434
NC_141594.1          15890
Name: 1, dtype: int64

In [11]:
ac_gtf["chrom_length"] = ac_gtf["Chromosome"].map(ac_genome_length)
ac_gtf

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,db_xref,description,gbkey,gene,gene_biotype,gene_synonym,partial,chrom_length
0,NC_083852.1,Gnomon,gene,19209,25539,.,+,.,LOC107992805,GeneID:107992805,MATH and LRR domain-containing protein PFE0570w,Gene,LOC107992805,protein_coding,NaN,NaN,27131825
1,NC_083852.1,Gnomon,gene,31867,34512,.,+,.,LOC107992868,GeneID:107992868,E3 ubiquitin-protein ligase RFWD3,Gene,LOC107992868,protein_coding,NaN,NaN,27131825
2,NC_083852.1,Gnomon,gene,38244,46847,.,+,.,LOC107992788,GeneID:107992788,ribose-phosphate pyrophosphokinase 1,Gene,LOC107992788,protein_coding,NaN,NaN,27131825
3,NC_083852.1,Gnomon,gene,50438,53323,.,+,.,LOC133667054,GeneID:133667054,"medium-chain specific acyl-CoA dehydrogenase, ...",Gene,LOC133667054,protein_coding,NaN,NaN,27131825
4,NC_083852.1,Gnomon,gene,53446,115364,.,+,.,LOC107992756,GeneID:107992756,nuclear hormone receptor FTZ-F1,Gene,LOC107992756,protein_coding,NaN,NaN,27131825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12543,NW_026893559.1,Gnomon,gene,230125,230503,.,+,.,LOC133667677,GeneID:133667677,uncharacterized LOC133667677,Gene,LOC133667677,protein_coding,NaN,NaN,250740
12544,NW_026893559.1,Gnomon,gene,52880,62536,.,-,.,LOC133667674,GeneID:133667674,uncharacterized LOC133667674,Gene,LOC133667674,protein_coding,NaN,NaN,250740
12545,NW_026893559.1,Gnomon,gene,233705,238437,.,-,.,LOC133667678,GeneID:133667678,uncharacterized LOC133667678,Gene,LOC133667678,protein_coding,NaN,NaN,250740
12546,NW_026893559.1,Gnomon,gene,239924,242142,.,-,.,LOC133667679,GeneID:133667679,uncharacterized LOC133667679,Gene,LOC133667679,protein_coding,NaN,NaN,250740
12547,NW_026893561.1,Gnomon,gene,31282,31660,.,+,.,LOC133667710,GeneID:133667710,uncharacterized LOC133667710,Gene,LOC133667710,protein_coding,NaN,NaN,504434

In [15]:
sum(ac_gtf["chrom_length"].isna()) # 追加无误，继续

0

In [16]:
import numpy as np

plus = ac_gtf["Strand"] == "+"

ac_gtf["Neo_Start"] = np.where(plus, ac_gtf["Start"] - 5000, ac_gtf["End"] - 2001)
ac_gtf["Neo_End"]   = np.where(plus, ac_gtf["Start"] + 2001, ac_gtf["End"] + 5000)
ac_gtf

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,db_xref,description,gbkey,gene,gene_biotype,gene_synonym,partial,chrom_length,Neo_Start,Neo_End
0,NC_083852.1,Gnomon,gene,19209,25539,.,+,.,LOC107992805,GeneID:107992805,MATH and LRR domain-containing protein PFE0570w,Gene,LOC107992805,protein_coding,NaN,NaN,27131825,14209,21210
1,NC_083852.1,Gnomon,gene,31867,34512,.,+,.,LOC107992868,GeneID:107992868,E3 ubiquitin-protein ligase RFWD3,Gene,LOC107992868,protein_coding,NaN,NaN,27131825,26867,33868
2,NC_083852.1,Gnomon,gene,38244,46847,.,+,.,LOC107992788,GeneID:107992788,ribose-phosphate pyrophosphokinase 1,Gene,LOC107992788,protein_coding,NaN,NaN,27131825,33244,40245
3,NC_083852.1,Gnomon,gene,50438,53323,.,+,.,LOC133667054,GeneID:133667054,"medium-chain specific acyl-CoA dehydrogenase, ...",Gene,LOC133667054,protein_coding,NaN,NaN,27131825,45438,52439
4,NC_083852.1,Gnomon,gene,53446,115364,.,+,.,LOC107992756,GeneID:107992756,nuclear hormone receptor FTZ-F1,Gene,LOC107992756,protein_coding,NaN,NaN,27131825,48446,55447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12543,NW_026893559.1,Gnomon,gene,230125,230503,.,+,.,LOC133667677,GeneID:133667677,uncharacterized LOC133667677,Gene,LOC133667677,protein_coding,NaN,NaN,250740,225125,232126
12544,NW_026893559.1,Gnomon,gene,52880,62536,.,-,.,LOC133667674,GeneID:133667674,uncharacterized LOC133667674,Gene,LOC133667674,protein_coding,NaN,NaN,250740,60535,67536
12545,NW_026893559.1,Gnomon,gene,233705,238437,.,-,.,LOC133667678,GeneID:133667678,uncharacterized LOC133667678,Gene,LOC133667678,protein_coding,NaN,NaN,250740,236436,243437
12546,NW_026893559.1,Gnomon,gene,239924,242142,.,-,.,LOC133667679,GeneID:133667679,uncharacterized LOC133667679,Gene,LOC133667679,protein_coding,NaN,NaN,250740,240141,247142
12547,NW_026893561.1,Gnomon,gene,31282,31660,.,+,.,LOC133667710,GeneID:133667710,uncharacterized LOC133667710,Gene,LOC133667710,protein_coding,NaN,NaN,504434,26282,33283

#### 如果Neo_Start为负数，将其变成0，如果Neo_End超出了同行chrom_length，将其替换为chrom_length

In [18]:
ac_gtf["Neo_Start"] = ac_gtf["Neo_Start"].clip(lower=0)
ac_gtf["Neo_End"] = ac_gtf[["Neo_End", "chrom_length"]].min(axis=1)
ac_gtf

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,db_xref,description,gbkey,gene,gene_biotype,gene_synonym,partial,chrom_length,Neo_Start,Neo_End
0,NC_083852.1,Gnomon,gene,19209,25539,.,+,.,LOC107992805,GeneID:107992805,MATH and LRR domain-containing protein PFE0570w,Gene,LOC107992805,protein_coding,NaN,NaN,27131825,14209,21210
1,NC_083852.1,Gnomon,gene,31867,34512,.,+,.,LOC107992868,GeneID:107992868,E3 ubiquitin-protein ligase RFWD3,Gene,LOC107992868,protein_coding,NaN,NaN,27131825,26867,33868
2,NC_083852.1,Gnomon,gene,38244,46847,.,+,.,LOC107992788,GeneID:107992788,ribose-phosphate pyrophosphokinase 1,Gene,LOC107992788,protein_coding,NaN,NaN,27131825,33244,40245
3,NC_083852.1,Gnomon,gene,50438,53323,.,+,.,LOC133667054,GeneID:133667054,"medium-chain specific acyl-CoA dehydrogenase, ...",Gene,LOC133667054,protein_coding,NaN,NaN,27131825,45438,52439
4,NC_083852.1,Gnomon,gene,53446,115364,.,+,.,LOC107992756,GeneID:107992756,nuclear hormone receptor FTZ-F1,Gene,LOC107992756,protein_coding,NaN,NaN,27131825,48446,55447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12543,NW_026893559.1,Gnomon,gene,230125,230503,.,+,.,LOC133667677,GeneID:133667677,uncharacterized LOC133667677,Gene,LOC133667677,protein_coding,NaN,NaN,250740,225125,232126
12544,NW_026893559.1,Gnomon,gene,52880,62536,.,-,.,LOC133667674,GeneID:133667674,uncharacterized LOC133667674,Gene,LOC133667674,protein_coding,NaN,NaN,250740,60535,67536
12545,NW_026893559.1,Gnomon,gene,233705,238437,.,-,.,LOC133667678,GeneID:133667678,uncharacterized LOC133667678,Gene,LOC133667678,protein_coding,NaN,NaN,250740,236436,243437
12546,NW_026893559.1,Gnomon,gene,239924,242142,.,-,.,LOC133667679,GeneID:133667679,uncharacterized LOC133667679,Gene,LOC133667679,protein_coding,NaN,NaN,250740,240141,247142
12547,NW_026893561.1,Gnomon,gene,31282,31660,.,+,.,LOC133667710,GeneID:133667710,uncharacterized LOC133667710,Gene,LOC133667710,protein_coding,NaN,NaN,504434,26282,33283

### 因为需要使用bedtools getfasta -s，所以必须保留Strand列：

In [19]:
ac_gtf_4_bed = ac_gtf[["Chromosome", "Neo_Start", "Neo_End", "gene_id", "Score", "Strand"]]
ac_gtf_4_bed

           Chromosome  Neo_Start  Neo_End       gene_id Score Strand
0         NC_083852.1      14209    21210  LOC107992805     .      +
1         NC_083852.1      26867    33868  LOC107992868     .      +
2         NC_083852.1      33244    40245  LOC107992788     .      +
3         NC_083852.1      45438    52439  LOC133667054     .      +
4         NC_083852.1      48446    55447  LOC107992756     .      +
...               ...        ...      ...           ...   ...    ...
12543  NW_026893559.1     225125   232126  LOC133667677     .      +
12544  NW_026893559.1      60535    67536  LOC133667674     .      -
12545  NW_026893559.1     236436   243437  LOC133667678     .      -
12546  NW_026893559.1     240141   247142  LOC133667679     .      -
12547  NW_026893561.1      26282    33283  LOC133667710     .      +

[12548 rows x 6 columns]

In [20]:
ac_gtf_4_bed.to_csv("./metadata/Acer_4_cisTarget.bed", sep="\t", index=False, header=False)

# 根据bed文件生成fasta

In [23]:
%%bash

bedtools getfasta \
    -fi "./fasta/Apis_cerana.fasta" \
    -bed "./metadata/Acer_4_cisTarget.bed" \
    -name \
    -s \
    -fo "./fasta/Apis_cerana_4_cisTarget.fasta"

In [ ]:
import pyfaidx

Am4cis = pyfaidx.Fasta("./fasta/Apis_cerana_4_cisTarget.fasta")
# 检查Apis_cerana_4_cisTarget.fasta.fai，确定长度是7001以保证bedtools没取错:

In [25]:
%%bash

head "./fasta/Apis_cerana_4_cisTarget.fasta.fai"

LOC107992805::NC_083852.1:14209-21210(+)	7001	42	7001	7002
LOC107992868::NC_083852.1:26867-33868(+)	7001	7086	7001	7002
LOC107992788::NC_083852.1:33244-40245(+)	7001	14130	7001	7002
LOC133667054::NC_083852.1:45438-52439(+)	7001	21174	7001	7002
LOC107992756::NC_083852.1:48446-55447(+)	7001	28218	7001	7002
LOC133667059::NC_083852.1:93406-100407(+)	7001	35263	7001	7002
LOC108004355::NC_083852.1:119392-126393(+)	7001	42309	7001	7002
LOC114576852::NC_083852.1:128607-135608(+)	7001	49355	7001	7002
LOC107992715::NC_083852.1:250011-257012(+)	7001	56401	7001	7002
LOC107992716::NC_083852.1:425494-432495(+)	7001	63447	7001	7002