前情提要：当项目进行到 pyscenic grn 的准备工作时，尝试使用果蝇的 TF 列表基于同源关系获取东方蜜蜂的 TF 列表。

此时，注意到果蝇-东方蜜蜂的 OrthoFinder 结果文件(tsv格式)中，果蝇使用的是 GTF 中的 gene_id，但蜜蜂使用的是 protein_id。

根据 OrthoFinder 的原理，可以推测，其原因是输入 OrthoFinder 中的蜜蜂 fasta，其 header 对应的是 protein_id 而非 gene_id。

那么，这将带来一个问题：如果蜜蜂 header 对应的是 protein_id 而非 gene_id，可能 OrthoFinder 之前的 primary_transcript 步骤就无法有效地去除 fasta 中属于同一基因的较短的转录本。这可能进一步导致同一基因的多个 isoform 被分到不同 Orthogroup。

In [4]:
%%bash

# 运行primary_transcript之前的蜜蜂fasta：
cp "/home/liuzhiyu/Projects/neo_caste/Find_Ortholog/proteomes/GCF_029169275.1_AcerK_1.0_protein.faa" "./orthofinder_output/GCF_029169275.1_AcerK_1.0_protein.faa"
# primary_transcript处理后的蜜蜂fasta：
cp "/home/liuzhiyu/Projects/neo_caste/Find_Ortholog/primary_transcripts/Apis_cerana.faa" "./orthofinder_output/Apis_cerana.faa"

du -sh "./orthofinder_output/GCF_029169275.1_AcerK_1.0_protein.faa"
du -sh "./orthofinder_output/Apis_cerana.faa"

25M	./orthofinder_output/GCF_029169275.1_AcerK_1.0_protein.faa
8.2M	./orthofinder_output/Apis_cerana.faa

根据文件的大小，可以确定 primary_transcript 确实对同一基因的短转录本进行了清理，但目前无法确定是否清理干净，需要验证。

我的想法是：先从蜜蜂 GTF 中提取各 gene_id 及其对应的各转录本 protein_id，以表格形式存储。然后获取 primary_transcript 处理后的蜜蜂 fasta 中的 protein_id，确定前者单个 gene_id 是否仅对应后者单个 protein_id，如果是，证明 primary_transcript 的处理可能是干净的。

In [2]:
%%bash

ln -sf "/home/liuzhiyu/Projects/neo_caste/fastq2matrix/Acer/ref/GCF_029169275.1_fixed.filtered.gtf" "./gtf/Apis_cerana.gtf"
gppy txinfo -g "./gtf/Apis_cerana.gtf" > "./gtf/Apis_cerana.tsv"

In [1]:
import pandas as pd

Acer_gtf = pd.read_csv("./gtf/Apis_cerana.tsv", sep="\t")
Acer_gid_pid = Acer_gtf[["gene", "protein_id"]].drop_duplicates()
Acer_gid_pid

/tmp/ipykernel_47999/2772417620.py:3: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  Acer_gtf = pd.read_csv("./gtf/Apis_cerana.tsv", sep="\t")

               gene      protein_id
0      LOC107992807  XP_016904367.1
1      LOC107992807  XP_016904368.1
2      LOC107992805  XP_061938525.1
3      LOC107992805  XP_061938550.1
4      LOC107992805  XP_061938560.1
...             ...             ...
34710           ND4  YP_003735177.1
34711          ND4L  YP_003735178.1
34712           ND6  YP_003735179.1
34713          CYTB  YP_003735180.1
34714           ND1  YP_003735181.1

[32356 rows x 2 columns]

In [2]:
from pyfaidx import Fasta

Acer_faa = Fasta("./orthofinder_output/Apis_cerana.faa")
Acer_faa_header_set = set(Acer_faa.keys())
Acer_faa_header_set

{'XP_028520122.1',
 'XP_016920836.1',
 'XP_061934535.1',
 'XP_061936518.1',
 'XP_061932386.1',
 'XP_061942643.1',
 'XP_016918557.1',
 'XP_016918395.1',
 'XP_061939137.1',
 'XP_061941369.1',
 'XP_016914972.1',
 'XP_061941732.1',
 'XP_016914682.1',
 'XP_016904308.2',
 'XP_016919393.2',
 'XP_016910682.1',
 'XP_016914794.2',
 'XP_016906944.2',
 'XP_016919530.1',
 'XP_016915862.2',
 'XP_028520668.2',
 'XP_061939225.1',
 'XP_016909883.2',
 'XP_061937709.1',
 'XP_016906850.1',
 'XP_016911464.1',
 'XP_016907082.2',
 'XP_016908701.1',
 'XP_016909757.1',
 'XP_016915127.1',
 'XP_061931859.1',
 'XP_016918925.1',
 'XP_061936360.1',
 'XP_061939598.1',
 'XP_061942978.1',
 'XP_016903917.1',
 'XP_061931080.1',
 'XP_016909087.2',
 'XP_061942584.1',
 'XP_016915185.1',
 'XP_016919701.1',
 'XP_016922417.1',
 'XP_061935835.1',
 'XP_061937700.1',
 'XP_016918774.2',
 'XP_016903957.1',
 'XP_061936842.1',
 'XP_028525710.1',
 'XP_016907115.1',
 'XP_016906527.1',
 'XP_061929607.1',
 'XP_028524099.2',
 'XP_061933879.1',
 'XP_016911968.2',
 'XP_061935325.1',
 'XP_016919499.1',
 'XP_061939894.1',
 'XP_061932848.1',
 'XP_016908356.1',
 'XP_016912041.1',
 'XP_016917986.1',
 'XP_016910444.1',
 'XP_016914203.1',
 'XP_061931817.1',
 'XP_016922834.1',
 'XP_016905958.1',
 'XP_016909124.1',
 'XP_061935652.1',
 'XP_061935766.1',
 'XP_016917439.2',
 'XP_028520224.2',
 'XP_061929543.1',
 'XP_016912965.2',
 'XP_016913375.2',
 'XP_016920273.1',
 'XP_016904116.1',
 'XP_016913918.1',
 'XP_016913764.1',
 'XP_016916168.1',
 'XP_016911923.1',
 'XP_061928652.1',
 'XP_061934745.1',
 'XP_061932925.1',
 'XP_016912877.1',
 'XP_061934978.1',
 'XP_061942875.1',
 'XP_016921590.2',
 'XP_016921752.2',
 'XP_028522571.1',
 'XP_061931318.1',
 'XP_016905953.2',
 'XP_028521372.1',
 'XP_061940202.1',
 'XP_028524870.1',
 'XP_016921603.1',
 'XP_016908345.1',
 'XP_061942551.1',
 'XP_016905117.1',
 'XP_061942521.1',
 'XP_061940599.1',
 'XP_016916210.2',
 'XP_028525707.1',
 'XP_016907256.1',
 'XP_016905534.1',
 'XP_016911514.1',
 'XP_061942898.1',
 'XP_061937398.1',
 'XP_061930907.1',
 'XP_061940225.1',
 'XP_016912380.1',
 'XP_061932042.1',
 'XP_016903984.1',
 'XP_061939586.1',
 'XP_016913146.1',
 'XP_016904670.1',
 'XP_061929248.1',
 'XP_016906925.1',
 'XP_016911778.1',
 'XP_016915447.1',
 'XP_061935591.1',
 'XP_061938831.1',
 'XP_016905382.2',
 'XP_016909671.2',
 'XP_016912989.2',
 'XP_061933575.1',
 'XP_061934567.1',
 'XP_016912548.1',
 'XP_028520209.1',
 'XP_061928475.1',
 'XP_061935833.1',
 'XP_016904053.1',
 'XP_061927168.1',
 'XP_016909549.2',
 'XP_061927971.1',
 'XP_061943033.1',
 'XP_016908159.1',
 'XP_016914066.1',
 'XP_061938226.1',
 'XP_016916683.1',
 'XP_016907071.2',
 'XP_061932666.1',
 'XP_061932788.1',
 'XP_016921376.2',
 'XP_016914226.1',
 'XP_061942589.1',
 'XP_016915526.1',
 'XP_016909220.1',
 'XP_028521760.2',
 'XP_016910718.1',
 'XP_061931855.1',
 'XP_061940482.1',
 'XP_061940598.1',
 'XP_016903971.1',
 'XP_061933679.1',
 'XP_061937879.1',
 'XP_061932402.1',
 'XP_061938246.1',
 'XP_028522377.1',
 'XP_061943419.1',
 'XP_016909820.1',
 'XP_061933228.1',
 'XP_016913270.1',
 'XP_061934537.1',
 'XP_016905090.1',
 'XP_016904709.2',
 'XP_016922844.1',
 'XP_016915394.2',
 'XP_016919461.2',
 'XP_028521976.2',
 'XP_016909115.2',
 'XP_061933963.1',
 'XP_016917219.1',
 'XP_061939743.1',
 'XP_016906453.1',
 'XP_016906514.2',
 'XP_016909906.1',
 'XP_016911060.1',
 'XP_016910864.2',
 'XP_061939502.1',
 'XP_016917440.1',
 'XP_016905779.1',
 'XP_061941109.1',
 'XP_016905272.1',
 'XP_061927960.1',
 'XP_061943361.1',
 'XP_061931156.1',
 'XP_016915292.2',
 'XP_016915856.1',
 'XP_061941507.1',
 'XP_061933913.1',
 'XP_028524509.1',
 'XP_028525306.2',
 'XP_016922906.1',
 'XP_016915647.1',
 'XP_061934324.1',
 'XP_061938711.1',
 'XP_061943092.1',
 'XP_028524845.2',
 'XP_061941648.1',
 'XP_061942500.1',
 'XP_016922749.1',
 'XP_016905978.1',
 'XP_016904282.1',
 'XP_061927603.1',
 'XP_016917894.2',
 'XP_061940869.1',
 'XP_016905808.1',
 'XP_016921822.1',
 'XP_016914540.1',
 'XP_016920935.2',
 'XP_016904461.1',
 'XP_016905108.1',
 'XP_016906895.1',
 'XP_016913524.1',
 'XP_016914703.1',
 'XP_016921574.2',
 'XP_016920035.1',
 'XP_061932750.1',
 'XP_061933309.1',
 'XP_061937608.1',
 'XP_016905347.2',
 'XP_016915328.1',
 'XP_061929291.1',
 'XP_016907562.1',
 'XP_061927689.1',
 'XP_061942305.1',
 'XP_016911758.1',
 'XP_016910771.1',
 'XP_016922463.1',
 'XP_061940560.1',
 'XP_016908590.1',
 'XP_016913858.1',
 'XP_028522535.1',
 'XP_061940836.1',
 'XP_061931510.1',
 'XP_016922714.1',
 'XP_061926878.1',
 'XP_061928041.1',
 'XP_061942135.1',
 'XP_016909345.1',
 'XP_061927633.1',
 'XP_016909214.2',
 'XP_061929102.1',
 'XP_016916815.1',
 'XP_016909223.1',
 'XP_061930985.1',
 'XP_016921609.2',
 'XP_016916669.1',
 'XP_028521703.2',
 'XP_061937884.1',
 'XP_061936527.1',
 'XP_061942188.1',
 'XP_016908896.1',
 'XP_016909370.1',
 'XP_016921417.1',
 'XP_061933371.1',
 'XP_061935868.1',
 'XP_016915037.1',
 'XP_016919532.1',
 'XP_016921005.1',
 'XP_061931554.1',
 'XP_061933530.1',
 'XP_061941883.1',
 'XP_061934044.1',
 'XP_016921482.1',
 'XP_061927041.1',
 'XP_016909826.1',
 'XP_061939122.1',
 'XP_061943302.1',
 'XP_016920665.1',
 'XP_061941273.1',
 'XP_016905383.1',
 'XP_016909186.2',
 'YP_003735172.1',
 'XP_016920198.2',
 'XP_016921780.1',
 'XP_028521767.1',
 'XP_028521627.1',
 'XP_028521273.1',
 'XP_028522847.1',
 'XP_061935142.1',
 'XP_016914183.1',
 'XP_016913881.2',
 'XP_016922949.1',
 'XP_016912412.1',
 'XP_061936692.1',
 'XP_061941530.1',
 'XP_016917992.1',
 'XP_016909967.2',
 'XP_016918617.1',
 'XP_061940824.1',
 'XP_016906630.2',
 'XP_061940389.1',
 'XP_016919722.1',
 'XP_016905093.1',
 'XP_016907511.1',
 'XP_016915125.1',
 'XP_061929735.1',
 'XP_061935728.1',
 'XP_061929659.1',
 'XP_016917979.1',
 'XP_016907053.1',
 'XP_016911399.1',
 'XP_016914846.3',
 'XP_016922785.2',
 'XP_028520264.1',
 'XP_061927570.1',
 'XP_016920079.2',
 'XP_028521266.2',
 'XP_061929918.1',
 'XP_061936123.1',
 'XP_061938174.1',
 'XP_061929604.1',
 'XP_016910426.2',
 'XP_016913479.1',
 'XP_061927937.1',
 'XP_016918637.1',
 'XP_016911757.1',
 'XP_061931856.1',
 'XP_016908135.3',
 'XP_016916543.2',
 'XP_016913164.2',
 'XP_061927694.1',
 'XP_016915066.1',
 'XP_061941229.1',
 'XP_016920038.1',
 'XP_016909371.1',
 'XP_016907728.1',
 'XP_061929357.1',
 'XP_016910722.2',
 'XP_061930036.1',
 'XP_061931682.1',
 'XP_028523672.1',
 'XP_028520121.1',
 'XP_016906571.1',
 'XP_028522592.2',
 'XP_061934987.1',
 'XP_016910320.1',
 'XP_016921356.1',
 'XP_061928499.1',
 'XP_061942233.1',
 'XP_061942442.1',
 'XP_016914485.1',
 'XP_016910912.1',
 'XP_016908011.1',
 'XP_061928374.1',
 'XP_016915971.1',
 'XP_061937805.1',
 'XP_016904815.1',
 'XP_016917893.2',
 'XP_028525209.1',
 'XP_016918851.1',
 'XP_016915462.1',
 'XP_016920398.1',
 'XP_061931540.1',
 'XP_061935515.1',
 'XP_061939298.1',
 'XP_061942228.1',
 'XP_028521193.2',
 'XP_016913610.2',
 'XP_061929752.1',
 'XP_061935931.1',
 'XP_016915342.1',
 'XP_061929882.1',
 'XP_016905465.2',
 'XP_061936229.1',
 'XP_061936020.1',
 'XP_016913374.2',
 'XP_016905830.1',
 'XP_061934747.1',
 'XP_016912642.1',
 'XP_028522092.1',
 'XP_061937209.1',
 'XP_061939120.1',
 'XP_061929115.1',
 'XP_016914745.1',
 'XP_016914885.1',
 'XP_016907829.1',
 'XP_016914105.1',
 'XP_016915722.1',
 'XP_016913723.1',
 'XP_028520970.1',
 'XP_028522596.2',
 'XP_061941386.1',
 'XP_061935017.1',
 'XP_061930837.1',
 'XP_061928269.1',
 'XP_061933108.1',
 'XP_061927945.1',
 'XP_061928114.1',
 'XP_061927615.1',
 'XP_061931877.1',
 'XP_061935359.1',
 'XP_016904506.1',
 'XP_016911184.1',
 'XP_061942788.1',
 'XP_016905577.1',
 'XP_061938881.1',
 'XP_061927002.1',
 'XP_061936978.1',
 'XP_016911482.1',
 'XP_016920488.1',
 'XP_016914036.1',
 'XP_061937866.1',
 'XP_061931783.1',
 'XP_061941278.1',
 'XP_061932257.1',
 'XP_016922064.2',
 'XP_061941813.1',
 'XP_061928768.1',
 'XP_028521827.1',
 'XP_016919304.1',
 'XP_016910382.1',
 'XP_061931848.1',
 'XP_016922386.2',
 'XP_061927861.1',
 'XP_016919288.1',
 'XP_061943132.1',
 'XP_016905583.2',
 'XP_061932427.1',
 'XP_061936460.1',
 'XP_061931434.1',
 'XP_016907717.1',
 'XP_061942676.1',
 'XP_016912377.1',
 'XP_016904706.1',
 'XP_016920381.1',
 'XP_016921299.1',
 'XP_061928013.1',
 'XP_061940157.1',
 'XP_061928826.1',
 'XP_016910045.2',
 'XP_016918514.1',
 'XP_028520877.1',
 'XP_061941490.1',
 'XP_061936712.1',
 'XP_016917121.1',
 'XP_061940798.1',
 'XP_016913299.1',
 'XP_016904917.1',
 'XP_061929816.1',
 'XP_016916698.1',
 'XP_061934085.1',
 'XP_016906230.1',
 'XP_061936727.1',
 'XP_016904006.1',
 'XP_016913138.2',
 'XP_016917057.1',
 'XP_016917629.1',
 'XP_061927124.1',
 'XP_061935561.1',
 'XP_016915167.1',
 'XP_061935143.1',
 'XP_061929024.1',
 'XP_016911910.3',
 'XP_016916777.1',
 'XP_016922152.1',
 'XP_016904595.2',
 'XP_016917612.1',
 'XP_016918335.2',
 'XP_016917859.2',
 'XP_016906390.1',
 'XP_016908605.1',
 'XP_061942306.1',
 'XP_016918061.2',
 'XP_016918413.1',
 'XP_016917902.1',
 'XP_028525355.2',
 'XP_061926939.1',
 'XP_061935982.1',
 'XP_061928046.1',
 'XP_016904256.1',
 'XP_016919057.1',
 'XP_016921430.2',
 'XP_016908577.1',
 'XP_061927089.1',
 'XP_016907923.1',
 'XP_016919695.2',
 'XP_061929467.1',
 'XP_016909950.2',
 'XP_016904201.2',
 'XP_016920126.1',
 'XP_061930080.1',
 'XP_016912316.1',
 'XP_016921149.1',
 'XP_016904915.2',
 'XP_016915800.1',
 'XP_016903775.2',
 'XP_016909723.1',
 'XP_016912021.2',
 'XP_016908158.2',
 'XP_016920054.1',
 'XP_016922897.2',
 'XP_016915122.1',
 'XP_016907255.1',
 'XP_016908379.1',
 'XP_016909291.1',
 'XP_016916131.1',
 'XP_061929366.1',
 'XP_016910051.2',
 'XP_016908723.2',
 'XP_061932897.1',
 'XP_061934245.1',
 'XP_016909928.1',
 'XP_016912547.1',
 'XP_061938240.1',
 'XP_016907825.2',
 'XP_028519922.2',
 'XP_061937921.1',
 'XP_061932998.1',
 'XP_016907484.1',
 'XP_016909684.1',
 'XP_061941393.1',
 'XP_016920006.1',
 'XP_061934821.1',
 'XP_016916108.1',
 'XP_061932399.1',
 'XP_016910853.1',
 'XP_061931628.1',
 'XP_061936706.1',
 'XP_016909938.1',
 'XP_016905437.1',
 'XP_016922237.1',
 'XP_061927951.1',
 'XP_061929768.1',
 'XP_061929953.1',
 'XP_016912601.1',
 'XP_016914239.1',
 'XP_061932351.1',
 'XP_061943058.1',
 'XP_016904250.1',
 'XP_016906888.1',
 'XP_016914748.1',
 'XP_016906924.1',
 'XP_061930892.1',
 'XP_061932006.1',
 'XP_061931723.1',
 'XP_016910923.1',
 'XP_016913187.1',
 'XP_016907073.2',
 'XP_016908139.3',
 'XP_016911397.2',
 'XP_016913907.1',
 'XP_016914569.1',
 'XP_016909163.1',
 'XP_016920719.2',
 'XP_016913963.1',
 'XP_016920952.1',
 'XP_061936848.1',
 'XP_061937966.1',
 'XP_061942853.1',
 'XP_061931821.1',
 'XP_016914747.1',
 'XP_016917788.2',
 'XP_016908323.1',
 'XP_016911063.1',
 'XP_016907000.2',
 'XP_016904597.1',
 'XP_061928119.1',
 'XP_061929871.1',
 'XP_016917154.1',
 'XP_061932067.1',
 'XP_016904953.1',
 'XP_016913366.1',
 'XP_016919112.1',
 'XP_016913647.1',
 'XP_016922907.1',
 'XP_016914543.2',
 'XP_028522697.1',
 'XP_061942861.1',
 'XP_061935052.1',
 'XP_016922067.1',
 'XP_061930349.1',
 'XP_016909471.1',
 'XP_016915094.1',
 'XP_061939166.1',
 'XP_016910590.1',
 'XP_016914992.1',
 'XP_016915663.2',
 'XP_061934025.1',
 'XP_016918170.2',
 'XP_016912831.1',
 'XP_016922611.1',
 'XP_061936470.1',
 'XP_061932382.1',
 'XP_016916864.1',
 'XP_061933923.1',
 'XP_016912818.1',
 'XP_061929222.1',
 'XP_016912256.1',
 'XP_016920419.2',
 'XP_061942509.1',
 'XP_061927717.1',
 'XP_016917230.1',
 'XP_061939508.1',
 'XP_028522563.1',
 'XP_016915259.1',
 'XP_061942710.1',
 'XP_028524047.2',
 'XP_016907316.1',
 'XP_016905482.1',
 'XP_016917443.1',
 'XP_061932424.1',
 'XP_061934994.1',
 'XP_016916403.1',
 'XP_016916526.1',
 'XP_061926955.1',
 'XP_061940877.1',
 'XP_016916510.1',
 'XP_061935460.1',
 'XP_016904374.2',
 'XP_061940191.1',
 'XP_016914817.1',
 'XP_016905354.1',
 'XP_016906440.2',
 'XP_016909362.1',
 'XP_016917605.1',
 'XP_016908018.2',
 'XP_016910739.1',
 'XP_016921427.1',
 'XP_016917754.1',
 'XP_016917823.2',
 'XP_016906021.1',
 'XP_028522064.2',
 'XP_061935289.1',
 'XP_016922511.1',
 'XP_061943341.1',
 'XP_061941404.1',
 'XP_061931942.1',
 'XP_016919375.1',
 'XP_061930280.1',
 'XP_016913333.2',
 'XP_016914429.2',
 'XP_061927114.1',
 'XP_016912843.1',
 'XP_061935710.1',
 'XP_061939158.1',
 'XP_061941235.1',
 'XP_016917838.1',
 'XP_016913849.1',
 'XP_016908627.2',
 'XP_061932714.1',
 'XP_016908987.1',
 'XP_061942130.1',
 'XP_016912542.1',
 'XP_061929198.1',
 'XP_016909756.1',
 'XP_016911772.1',
 'XP_061929552.1',
 'XP_016908459.1',
 'XP_061934748.1',
 'XP_016909800.1',
 'XP_016911719.1',
 'XP_061940920.1',
 'XP_016909787.1',
 'XP_061933591.1',
 'XP_061938501.1',
 'XP_061936216.1',
 'XP_016908512.1',
 'XP_016906574.1',
 'XP_016916199.1',
 'XP_016911064.1',
 'XP_061938228.1',
 'XP_016920353.1',
 'XP_061930090.1',
 'XP_016906865.1',
 'XP_016916467.1',
 'XP_016916380.1',
 'XP_016911549.1',
 'XP_016917220.1',
 'XP_016920944.1',
 'XP_061930930.1',
 'XP_061940327.1',
 'XP_016905334.1',
 'XP_016919306.1',
 'XP_061937711.1',
 'XP_016909779.2',
 'XP_016916130.1',
 'XP_061942447.1',
 'XP_061936497.1',
 'XP_061937208.1',
 'XP_016912716.1',
 'XP_016919795.1',
 'XP_016920933.2',
 'XP_028520398.1',
 'XP_016921103.1',
 'XP_016904287.1',
 'XP_016921389.2',
 'XP_061931992.1',
 'XP_016921834.1',
 'XP_016917260.2',
 'XP_028524219.1',
 'XP_061933439.1',
 'XP_016907078.1',
 'XP_016911589.1',
 'XP_061927501.1',
 'XP_061935725.1',
 'XP_016919588.1',
 'XP_016912457.2',
 'XP_061941240.1',
 'XP_061929063.1',
 'XP_061928581.1',
 'XP_061937207.1',
 'XP_061942798.1',
 'XP_061929797.1',
 'XP_061928486.1',
 'XP_061936708.1',
 'XP_016914124.2',
 'XP_016920320.1',
 'XP_016917207.1',
 'XP_016910862.1',
 'XP_016912215.1',
 'XP_061935466.1',
 'XP_028523341.1',
 'XP_061937649.1',
 'XP_016920794.1',
 'XP_061941640.1',
 'XP_016914156.1',
 'XP_016907237.1',
 'XP_061931397.1',
 'XP_028523457.1',
 'XP_016913427.2',
 'XP_016919209.1',
 'XP_016916190.1',
 'XP_061929639.1',
 'XP_061930069.1',
 'XP_016917003.1',
 'XP_061941826.1',
 'XP_061941744.1',
 'XP_016910028.2',
 'XP_016905587.2',
 'XP_016908190.2',
 'XP_016914624.1',
 'XP_016910919.2',
 'XP_016911095.1',
 'XP_061937693.1',
 'XP_061943265.1',
 'XP_016914292.2',
 'XP_061939442.1',
 'XP_016906350.1',
 'XP_061934774.1',
 'XP_061931621.1',
 'XP_061935789.1',
 'XP_061933114.1',
 'XP_061936720.1',
 'XP_061927645.1',
 'XP_061937527.1',
 'XP_016919897.1',
 'XP_061935041.1',
 'XP_061927243.1',
 'XP_061931907.1',
 'XP_061933245.1',
 'XP_016906168.1',
 'XP_061937361.1',
 'XP_016906166.1',
 'XP_061933491.1',
 'XP_016915890.1',
 'XP_061929477.1',
 'XP_061932415.1',
 'XP_016915165.1',
 'XP_061931906.1',
 'XP_061937492.1',
 'XP_016914731.2',
 'XP_061930996.1',
 'XP_061932309.1',
 'XP_016912221.1',
 'XP_061929220.1',
 'XP_028522931.2',
 'XP_061943089.1',
 'XP_016913326.1',
 'XP_016906249.1',
 'XP_016906788.1',
 'XP_016921724.2',
 'XP_028524760.2',
 'XP_016915010.1',
 'XP_016917007.1',
 'XP_016906384.1',
 'XP_061935004.1',
 'XP_016910166.2',
 'XP_061935239.1',
 'XP_061941426.1',
 'XP_061937595.1',
 'XP_016915371.1',
 'XP_061943196.1',
 'XP_016920729.1',
 'XP_016912055.1',
 'XP_016909057.1',
 'XP_016914120.1',
 'XP_028520219.1',
 'XP_061938052.1',
 'XP_061932366.1',
 'XP_016906704.1',
 'XP_061934927.1',
 'XP_061929936.1',
 'XP_016909261.2',
 'XP_016907646.1',
 'XP_061932898.1',
 'XP_028523769.1',
 'XP_061933741.1',
 'XP_016915629.2',
 'XP_016915283.2',
 'XP_061936484.1',
 'XP_016915920.1',
 'XP_061931402.1',
 'XP_061928111.1',
 'XP_016915981.2',
 'XP_061927035.1',
 'XP_016913910.1',
 'XP_016910343.1',
 'XP_061932605.1',
 'XP_061935595.1',
 'XP_061934203.1',
 'XP_016913926.1',
 'XP_016912274.1',
 'XP_016920295.1',
 'XP_016922653.1',
 'XP_016910200.1',
 'XP_016913047.1',
 'XP_016918757.2',
 'XP_016920548.2',
 'XP_016921336.1',
 'XP_016910096.1',
 'XP_061928253.1',
 'XP_061933902.1',
 'XP_061931835.1',
 'XP_061930976.1',
 'XP_061937551.1',
 'XP_061934671.1',
 'XP_016921595.2',
 'XP_061932146.1',
 'XP_028522460.1',
 'XP_061927573.1',
 'XP_061941241.1',
 'XP_061941491.1',
 'XP_016916446.2',
 'XP_061936383.1',
 'XP_016919856.2',
 'XP_061936362.1',
 'XP_016905675.1',
 'XP_016903746.1',
 'XP_061927691.1',
 'XP_028520105.1',
 'XP_016908794.2',
 'XP_061928151.1',
 'XP_016919750.2',
 'XP_061930005.1',
 'XP_016908671.1',
 'XP_016911251.1',
 'XP_016913688.2',
 'XP_016914808.1',
 'XP_061936893.1',
 'XP_061935202.1',
 'XP_028520307.2',
 'XP_016918743.1',
 'XP_016920471.1',
 'XP_061936841.1',
 'XP_016904493.1',
 'XP_061929743.1',
 'XP_061932305.1',
 'XP_016908680.1',
 'XP_016908740.1',
 'XP_016915380.1',
 'XP_016918437.1',
 'XP_016913095.2',
 'XP_016915872.1',
 'XP_061930906.1',
 'XP_016918226.1',
 'XP_061939125.1',
 'XP_016914642.1',
 'XP_061935471.1',
 'XP_061942539.1',
 'XP_061931112.1',
 'XP_016917372.2',
 'XP_061929195.1',
 'XP_016917779.1',
 'XP_061931778.1',
 'XP_028521108.2',
 'XP_061933735.1',
 'XP_016906012.1',
 'XP_061942199.1',
 'XP_016910239.1',
 'XP_061931002.1',
 'XP_061929282.1',
 'XP_016906837.1',
 'XP_016921910.2',
 'XP_016915605.2',
 'XP_061932321.1',
 'XP_061937493.1',
 'XP_028525383.1',
 'XP_061928328.1',
 'XP_061941012.1',
 'XP_016919046.2',
 'XP_061935010.1',
 'XP_016906014.1',
 'XP_016911811.1',
 'XP_061937564.1',
 'XP_016908174.1',
 'XP_061941433.1',
 'XP_016920352.1',
 'XP_016910110.1',
 'XP_061929976.1',
 'XP_016907305.1',
 'XP_016906757.1',
 'XP_016909521.1',
 'XP_061928461.1',
 'XP_061929555.1',
 'XP_061930074.1',
 'XP_061938300.1',
 'XP_016909706.1',
 'XP_061928295.1',
 'XP_028524372.1',
 'XP_016910173.2',
 'XP_061943339.1',
 'XP_016908316.1',
 'XP_016908789.1',
 'XP_016909159.1',
 'XP_061929341.1',
 'XP_061939313.1',
 'XP_016918862.1',
 'XP_061941220.1',
 'XP_016915373.1',
 'XP_016916152.1',
 'XP_016920269.2',
 'XP_061936503.1',
 'XP_061936846.1',
 'XP_016904779.2',
 'XP_061928201.1',
 'XP_061929792.1',
 'XP_061936001.1',
 'XP_028523845.1',
 'XP_016908806.1',
 'XP_061928322.1',
 'XP_016917374.1',
 'XP_016917487.1',
 'XP_016914788.1',
 'XP_016922194.2',
 'XP_061930932.1',
 'XP_061938411.1',
 'XP_016917457.1',
 'XP_061934382.1',
 'XP_016906323.2',
 'XP_016909344.1',
 'XP_061931398.1',
 'XP_028520749.2',
 'XP_061927055.1',
 'XP_061934248.1',
 'XP_016919533.1',
 'XP_061939302.1',
 'XP_016903885.1',
 'XP_061930888.1',
 'XP_061927842.1',
 'XP_016907753.1',
 'XP_016904310.1',
 'XP_016905656.1',
 'XP_016909340.1',
 'XP_061929106.1',
 'XP_016905476.1',
 'XP_061937563.1',
 'XP_061930442.1',
 'XP_016908960.2',
 'XP_061930224.1',
 'XP_061935040.1',
 'XP_016922514.1',
 'XP_016908553.2',
 'XP_016910054.2',
 'XP_061933787.1',
 'XP_016906841.1',
 'XP_016915199.1',
 'XP_061933270.1',
 'XP_028523283.2',
 'XP_016912243.1',
 'XP_061942544.1',
 'XP_061929478.1',
 'XP_016912905.1',
 'XP_016917475.2',
 'XP_016906582.1',
 'XP_016904263.1',
 'XP_061937471.1',
 'XP_016914828.1',
 'XP_061939597.1',
 'XP_061940290.1',
 'XP_016904395.1',
 'XP_061942545.1',
 'XP_016919764.1',
 'XP_016920540.2',
 'XP_016908990.1',
 'XP_061928115.1',
 'XP_061941905.1',
 'XP_061932919.1',
 'XP_061934985.1',
 'XP_016916744.1',
 'XP_016912487.1',
 'XP_016917050.2',
 'XP_016904331.1',
 'XP_016911345.1',
 'XP_028523343.1',
 'XP_016914216.2',
 'XP_016904442.1',
 'XP_061935407.1',
 'XP_016912939.1',
 ...}

In [3]:
Acer_gid_pid_infaa = Acer_gid_pid[Acer_gid_pid["protein_id"].isin(Acer_faa_header_set)]
Acer_gid_pid_infaa

               gene      protein_id
0      LOC107992807  XP_016904367.1
1      LOC107992807  XP_016904368.1
9      LOC107992806  XP_061938570.1
11     LOC107992868  XP_028520126.1
14     LOC107992792  XP_016904346.1
...             ...             ...
34710           ND4  YP_003735177.1
34711          ND4L  YP_003735178.1
34712           ND6  YP_003735179.1
34713          CYTB  YP_003735180.1
34714           ND1  YP_003735181.1

[12625 rows x 2 columns]

In [7]:
Acer_gid_pid_infaa["gene"].value_counts()

LOC107998865    18
LOC108001457    18
LOC108001506    17
LOC108001085    17
LOC108000242    15
                ..
LOC107997847     1
LOC107997846     1
LOC107997848     1
LOC107997849     1
ND1              1
Name: gene, Length: 9717, dtype: int64

↑ 综上，可见 primary_transcript 处理后的东方蜜蜂 fasta 中，同一基因有若干转录本，primary_transcript 并未保留单一的最长转录本，因此之前的 OrthoFinder 实践是不正确的。