In [12]:
from pyfaidx import Fasta
import pandas as pd
import re

In [6]:
Acer_gtf = pd.read_csv("./gtf/Apis_cerana.tsv", sep="\t")
Acer_gtf

/tmp/ipykernel_14222/2275275324.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  Acer_gtf = pd.read_csv("./gtf/Apis_cerana.tsv", sep="\t")

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,db_xref,exception,experiment,gbkey,gene,gene_biotype,inference,locus_tag,product,protein_id,transcript_biotype
0,XM_017048878.3,LOC107992807,NC_083852.1,-,6,713,312,197,204,GeneID:107992807,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992807,protein_coding,NaN,NaN,NaN,XP_016904367.1,mRNA
1,XM_017048879.3,LOC107992807,NC_083852.1,-,5,1167,312,651,204,GeneID:107992807,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992807,protein_coding,NaN,NaN,NaN,XP_016904368.1,mRNA
2,XM_062082541.1,LOC107992805,NC_083852.1,+,6,4095,3759,155,181,GeneID:107992805,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992805,protein_coding,NaN,NaN,NaN,XP_061938525.1,mRNA
3,XM_062082566.1,LOC107992805,NC_083852.1,+,7,4344,3717,446,181,GeneID:107992805,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992805,protein_coding,NaN,NaN,NaN,XP_061938550.1,mRNA
4,XM_062082576.1,LOC107992805,NC_083852.1,+,7,4339,3675,483,181,GeneID:107992805,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992805,protein_coding,NaN,NaN,NaN,XP_061938560.1,mRNA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34710,unassigned_transcript_252,KEH14_p05,NC_014295.1,-,1,1329,1329,0,0,NaN,NaN,NaN,mRNA,ND4,protein_coding,NaN,KEH14_p05,NaN,YP_003735177.1,mRNA
34711,unassigned_transcript_253,KEH14_p04,NC_014295.1,-,1,264,264,0,0,NaN,NaN,NaN,mRNA,ND4L,protein_coding,NaN,KEH14_p04,NaN,YP_003735178.1,mRNA
34712,unassigned_transcript_256,KEH14_p03,NC_014295.1,+,1,510,510,0,0,NaN,NaN,NaN,mRNA,ND6,protein_coding,NaN,KEH14_p03,NaN,YP_003735179.1,mRNA
34713,unassigned_transcript_257,KEH14_p02,NC_014295.1,+,1,1149,1149,0,0,NaN,NaN,NaN,mRNA,CYTB,protein_coding,NaN,KEH14_p02,NaN,YP_003735180.1,mRNA
34714,unassigned_transcript_259,KEH14_p01,NC_014295.1,-,1,915,915,0,0,NaN,NaN,NaN,mRNA,ND1,protein_coding,NaN,KEH14_p01,NaN,YP_003735181.1,mRNA

In [7]:
Acer_pid_gid = Acer_gtf[["protein_id", "gene_id"]]
Acer_pid_gid

           protein_id       gene_id
0      XP_016904367.1  LOC107992807
1      XP_016904368.1  LOC107992807
2      XP_061938525.1  LOC107992805
3      XP_061938550.1  LOC107992805
4      XP_061938560.1  LOC107992805
...               ...           ...
34710  YP_003735177.1     KEH14_p05
34711  YP_003735178.1     KEH14_p04
34712  YP_003735179.1     KEH14_p03
34713  YP_003735180.1     KEH14_p02
34714  YP_003735181.1     KEH14_p01

[34715 rows x 2 columns]

In [8]:
Acer_pid_gid[Acer_pid_gid["protein_id"].isna() | Acer_pid_gid["gene_id"].isna()]

      protein_id       gene_id
16           NaN  LOC107992788
17           NaN  LOC107992788
18           NaN  LOC107992788
33           NaN  LOC133667061
35           NaN  LOC107992759
...          ...           ...
34634        NaN  LOC133667571
34635        NaN  LOC133667556
34636        NaN  LOC133667556
34638        NaN  LOC133667621
34639        NaN  LOC133667555

[5527 rows x 2 columns]

In [9]:
Acer_faa = Fasta("./all_former_faa_origin/GCF_029169275.1_AcerK_1.0_protein.faa", read_long_names=True)
header_set = set(long_name.split(' ')[0] for long_name in Acer_faa.keys())
header_set

{'XP_016908141.1',
 'XP_061938497.1',
 'XP_061940889.1',
 'XP_016914862.2',
 'XP_061929238.1',
 'XP_016909772.1',
 'XP_061941928.1',
 'XP_016911593.1',
 'XP_061930430.1',
 'XP_061931768.1',
 'XP_061942959.1',
 'XP_061935668.1',
 'XP_061927190.1',
 'XP_061940036.1',
 'XP_061942794.1',
 'XP_061941221.1',
 'XP_028521862.1',
 'XP_016906816.1',
 'XP_061938238.1',
 'XP_028524757.1',
 'XP_016918868.2',
 'XP_016911595.2',
 'XP_016920284.1',
 'XP_061931989.1',
 'XP_061931071.1',
 'XP_061938018.1',
 'XP_061930448.1',
 'XP_016916226.1',
 'XP_016910667.1',
 'XP_061934007.1',
 'XP_016911895.2',
 'XP_016906495.1',
 'XP_061932992.1',
 'XP_016915161.1',
 'XP_016921205.2',
 'XP_061934420.1',
 'XP_061937248.1',
 'XP_061942237.1',
 'XP_061937543.1',
 'XP_061929991.1',
 'XP_061937459.1',
 'XP_016916748.2',
 'XP_061938878.1',
 'XP_016911173.2',
 'XP_061937512.1',
 'XP_061943179.1',
 'XP_016912174.1',
 'XP_061937176.1',
 'XP_061936420.1',
 'XP_016905424.2',
 'XP_016916383.1',
 'XP_061940279.1',
 'XP_016912229.1',
 'XP_061931455.1',
 'XP_028521618.2',
 'XP_061940421.1',
 'XP_061937643.1',
 'XP_016911478.1',
 'XP_016912319.1',
 'XP_061933939.1',
 'XP_016910948.1',
 'XP_061931049.1',
 'XP_016920436.1',
 'XP_061938781.1',
 'XP_028521225.1',
 'XP_061939413.1',
 'XP_028522176.1',
 'XP_061940870.1',
 'XP_016913323.1',
 'XP_016914179.1',
 'XP_061931782.1',
 'XP_061938435.1',
 'XP_016911205.1',
 'XP_016918546.1',
 'XP_061938340.1',
 'XP_016918315.1',
 'XP_016907699.1',
 'XP_016917157.1',
 'XP_061935159.1',
 'XP_061941747.1',
 'XP_061938487.1',
 'XP_016914885.1',
 'XP_061940929.1',
 'XP_016906563.1',
 'XP_061929059.1',
 'XP_061943222.1',
 'XP_061933144.1',
 'XP_061928822.1',
 'XP_016922121.2',
 'XP_028522884.2',
 'XP_016908206.1',
 'XP_028520527.1',
 'XP_016908232.2',
 'XP_061928207.1',
 'XP_061936347.1',
 'XP_061939504.1',
 'XP_061942600.1',
 'XP_016919073.1',
 'XP_061928594.1',
 'XP_061943380.1',
 'XP_061929496.1',
 'XP_061927998.1',
 'XP_061939390.1',
 'XP_016904393.2',
 'XP_016913000.2',
 'XP_061942587.1',
 'XP_016909835.2',
 'XP_061936646.1',
 'XP_016915955.1',
 'XP_061934101.1',
 'XP_016913147.1',
 'XP_028522900.1',
 'XP_016912382.1',
 'XP_061931852.1',
 'XP_061935540.1',
 'XP_061935384.1',
 'XP_061932327.1',
 'XP_016918125.1',
 'XP_016921651.1',
 'XP_061934557.1',
 'XP_061937356.1',
 'XP_061931148.1',
 'XP_016906629.1',
 'XP_061932955.1',
 'XP_061935482.1',
 'XP_061931130.1',
 'XP_016916411.1',
 'XP_061937611.1',
 'XP_016912520.1',
 'XP_061928759.1',
 'XP_016919353.2',
 'XP_061939633.1',
 'XP_061939635.1',
 'XP_061928772.1',
 'XP_061940963.1',
 'XP_028525369.1',
 'XP_061935275.1',
 'XP_028523768.1',
 'XP_016919839.1',
 'XP_061935472.1',
 'XP_061928683.1',
 'XP_061928819.1',
 'XP_061942739.1',
 'XP_016914207.1',
 'XP_016911597.2',
 'XP_028520202.1',
 'XP_016911974.1',
 'XP_061929956.1',
 'XP_061942081.1',
 'XP_061932447.1',
 'XP_061940958.1',
 'XP_016912021.2',
 'XP_061928725.1',
 'XP_061942879.1',
 'XP_061935234.1',
 'XP_061942097.1',
 'XP_061933746.1',
 'XP_016920381.1',
 'XP_016916954.1',
 'XP_061937876.1',
 'XP_016921727.2',
 'XP_016910080.1',
 'XP_016910887.1',
 'XP_061932404.1',
 'XP_016910072.1',
 'XP_061935886.1',
 'XP_061938226.1',
 'XP_028520041.1',
 'XP_061934780.1',
 'XP_061939476.1',
 'XP_061930988.1',
 'XP_016907515.1',
 'XP_061933655.1',
 'XP_016904624.2',
 'XP_028524138.1',
 'XP_061927434.1',
 'XP_061931252.1',
 'XP_016910348.3',
 'XP_061937723.1',
 'XP_016921171.1',
 'XP_061943247.1',
 'XP_016921149.1',
 'XP_061933588.1',
 'XP_016920192.1',
 'XP_061934412.1',
 'XP_061926912.1',
 'XP_061934060.1',
 'XP_061937065.1',
 'XP_061929173.1',
 'XP_061937959.1',
 'XP_061942241.1',
 'XP_016909643.2',
 'XP_016910418.1',
 'XP_061936466.1',
 'XP_016907694.1',
 'XP_016908184.1',
 'XP_016913915.1',
 'XP_061929753.1',
 'XP_016911482.1',
 'XP_016914351.2',
 'XP_061932019.1',
 'XP_061940112.1',
 'XP_061939954.1',
 'XP_061932413.1',
 'XP_028521189.2',
 'XP_061940953.1',
 'XP_061931539.1',
 'XP_016906600.1',
 'XP_061939948.1',
 'XP_061936750.1',
 'XP_061943089.1',
 'XP_016909856.1',
 'XP_061927941.1',
 'XP_016905938.2',
 'XP_016906767.1',
 'XP_061939488.1',
 'XP_061929699.1',
 'XP_061933700.1',
 'XP_061942425.1',
 'XP_028523896.1',
 'XP_061933920.1',
 'XP_016922463.1',
 'XP_061934584.1',
 'XP_061940641.1',
 'XP_016906511.1',
 'XP_061935080.1',
 'XP_061938477.1',
 'XP_061934851.1',
 'XP_016913100.1',
 'XP_061938361.1',
 'XP_016911685.1',
 'XP_061942127.1',
 'XP_016914203.1',
 'XP_016911760.1',
 'XP_028523676.1',
 'XP_061937689.1',
 'XP_016913386.1',
 'XP_016920242.2',
 'XP_028523261.1',
 'XP_016904777.1',
 'XP_061932146.1',
 'XP_016905522.1',
 'XP_028523895.1',
 'XP_061938616.1',
 'XP_016904856.1',
 'XP_028522562.1',
 'XP_016908048.1',
 'XP_016917207.1',
 'XP_016906818.1',
 'XP_061932721.1',
 'XP_028520215.1',
 'XP_061940509.1',
 'XP_061940374.1',
 'XP_061929299.1',
 'XP_016921232.2',
 'XP_016922327.1',
 'XP_061934815.1',
 'XP_016913004.1',
 'XP_016916418.1',
 'XP_061937818.1',
 'XP_061935009.1',
 'XP_016915844.1',
 'XP_061929894.1',
 'XP_061934757.1',
 'XP_016911837.1',
 'XP_061940975.1',
 'XP_016909273.2',
 'XP_061930437.1',
 'XP_061939853.1',
 'XP_016907484.1',
 'XP_061931225.1',
 'XP_061938538.1',
 'XP_016909075.1',
 'XP_061937973.1',
 'XP_061935444.1',
 'XP_061932517.1',
 'XP_061938983.1',
 'XP_061939141.1',
 'XP_061929516.1',
 'XP_016910684.1',
 'XP_016919558.1',
 'XP_016905000.1',
 'XP_016914774.1',
 'XP_061934297.1',
 'XP_061932222.1',
 'XP_016908848.2',
 'XP_016910903.1',
 'XP_061934304.1',
 'XP_016907797.1',
 'XP_061934185.1',
 'XP_016905068.2',
 'XP_061937517.1',
 'XP_061941283.1',
 'XP_061935823.1',
 'XP_061928557.1',
 'XP_061930696.1',
 'XP_061938444.1',
 'XP_016920539.1',
 'XP_061935342.1',
 'XP_028522508.1',
 'XP_016917789.2',
 'XP_061929011.1',
 'XP_061941861.1',
 'XP_016907071.2',
 'XP_061930963.1',
 'XP_061928243.1',
 'XP_016918216.1',
 'XP_016907789.1',
 'XP_028520749.2',
 'XP_061932516.1',
 'XP_061927014.1',
 'XP_061938997.1',
 'XP_028524538.2',
 'XP_016906286.1',
 'XP_061929969.1',
 'XP_016907115.1',
 'XP_016914143.1',
 'XP_061939727.1',
 'XP_016917949.1',
 'XP_016915311.1',
 'XP_028525421.1',
 'XP_061937780.1',
 'XP_061928941.1',
 'XP_061941703.1',
 'XP_016911393.1',
 'XP_016919788.1',
 'XP_061929910.1',
 'XP_016915617.1',
 'XP_061936694.1',
 'XP_061937495.1',
 'XP_061928994.1',
 'XP_016907268.1',
 'XP_016907224.1',
 'XP_061933468.1',
 'XP_028525202.2',
 'XP_016909666.2',
 'XP_061934352.1',
 'XP_016907042.1',
 'XP_061936209.1',
 'XP_061931365.1',
 'XP_016909671.2',
 'XP_061936863.1',
 'XP_061934357.1',
 'XP_061939600.1',
 'XP_061937041.1',
 'XP_028521318.1',
 'XP_061929966.1',
 'XP_061937074.1',
 'XP_016915126.1',
 'XP_061936136.1',
 'XP_061927470.1',
 'XP_016914607.1',
 'XP_061927273.1',
 'XP_028523550.2',
 'XP_016907568.2',
 'XP_061937024.1',
 'XP_016911064.1',
 'XP_016907825.2',
 'XP_061936091.1',
 'XP_061938345.1',
 'XP_016916284.1',
 'XP_016911037.1',
 'XP_061930182.1',
 'XP_061932427.1',
 'XP_061942291.1',
 'XP_016904148.1',
 'XP_016907324.2',
 'XP_061941079.1',
 'XP_016911188.1',
 'XP_016921366.1',
 'XP_061929370.1',
 'XP_016905475.1',
 'XP_061928787.1',
 'XP_061941556.1',
 'XP_016922815.1',
 'XP_016908049.2',
 'XP_061930483.1',
 'XP_061934612.1',
 'XP_016917843.1',
 'XP_061930802.1',
 'XP_061941824.1',
 'XP_016917249.1',
 'XP_061943115.1',
 'XP_016916350.2',
 'XP_016918894.1',
 'XP_061934576.1',
 'XP_016903966.1',
 'XP_028522762.1',
 'XP_016920236.2',
 'XP_028521619.2',
 'XP_061931898.1',
 'XP_016914943.1',
 'XP_061935049.1',
 'XP_016908804.1',
 'XP_061934849.1',
 'XP_016908622.1',
 'XP_061928103.1',
 'XP_016905612.1',
 'XP_061938013.1',
 'XP_061934473.1',
 'XP_061932156.1',
 'XP_061930531.1',
 'XP_016909897.2',
 'XP_016907191.1',
 'XP_016919093.1',
 'XP_016914217.2',
 'XP_061933343.1',
 'XP_016918229.1',
 'XP_061928383.1',
 'XP_061931290.1',
 'XP_061937605.1',
 'XP_061930760.1',
 'XP_016914139.1',
 'XP_061932252.1',
 'XP_061933246.1',
 'XP_061941850.1',
 'XP_061930418.1',
 'XP_016920960.1',
 'XP_016909626.3',
 'XP_016916372.1',
 'XP_016914373.1',
 'XP_061943388.1',
 'XP_028521966.1',
 'XP_016906193.1',
 'XP_061936743.1',
 'XP_061930524.1',
 'XP_061942792.1',
 'XP_016910036.1',
 'XP_016915393.1',
 'XP_061931156.1',
 'XP_061932326.1',
 'XP_061934647.1',
 'XP_061936204.1',
 'XP_061936260.1',
 'XP_016915627.2',
 'XP_061926828.1',
 'XP_016916809.2',
 'XP_016911863.1',
 'XP_061931230.1',
 'XP_016911483.1',
 'XP_061928418.1',
 'XP_061928392.1',
 'XP_016919169.1',
 'XP_061936376.1',
 'XP_061927695.1',
 'XP_061927077.1',
 'XP_016906250.1',
 'XP_016914908.1',
 'XP_061933906.1',
 'XP_061929850.1',
 'XP_061942748.1',
 'XP_061940141.1',
 'XP_061939534.1',
 'XP_061933333.1',
 'XP_016922439.1',
 'XP_061928329.1',
 'XP_016908153.1',
 'XP_061937365.1',
 'XP_028521631.2',
 'XP_061934850.1',
 'XP_016912692.2',
 'XP_016915977.1',
 'XP_061942497.1',
 'XP_016904782.1',
 'XP_061935532.1',
 'XP_016910616.1',
 'XP_061937456.1',
 'XP_016920782.1',
 'XP_028525456.2',
 'XP_016907838.2',
 'XP_016908168.2',
 'XP_061935892.1',
 'XP_016911656.1',
 'XP_061932808.1',
 'XP_016904920.1',
 'XP_016912270.1',
 'XP_016905557.1',
 'XP_016908226.2',
 'XP_016917836.1',
 'XP_061936142.1',
 'XP_028523817.2',
 'XP_061933337.1',
 'XP_061936679.1',
 'XP_061940058.1',
 'XP_061939171.1',
 'XP_016908591.2',
 'XP_061931608.1',
 'XP_061935025.1',
 'XP_016920716.2',
 'XP_016922105.2',
 'XP_028520236.1',
 'XP_061931891.1',
 'XP_061942729.1',
 'XP_061932680.1',
 'XP_016912132.1',
 'XP_016906917.1',
 'XP_061941598.1',
 'XP_016915108.1',
 'XP_016906776.1',
 'XP_061928466.1',
 'XP_028520265.1',
 'XP_061930614.1',
 'XP_061930309.1',
 'XP_061939001.1',
 'XP_061941838.1',
 'XP_016919924.1',
 'XP_028522278.2',
 'XP_061942415.1',
 'XP_061935724.1',
 'XP_061943060.1',
 'XP_061940854.1',
 'XP_061940685.1',
 'XP_061938099.1',
 'XP_061928504.1',
 'XP_061942980.1',
 'XP_061942489.1',
 'XP_016910383.3',
 'XP_061932235.1',
 'XP_016919649.1',
 'XP_061929638.1',
 'XP_016916440.2',
 'XP_016922157.1',
 'XP_061932394.1',
 'XP_016917140.1',
 'XP_061928190.1',
 'XP_061931056.1',
 'XP_016913992.1',
 'XP_061931623.1',
 'XP_028521490.1',
 'XP_016916673.1',
 'XP_016908463.2',
 'XP_061927759.1',
 'XP_061929461.1',
 'XP_016903833.2',
 'XP_016918896.1',
 'XP_028522792.1',
 'XP_061929504.1',
 'XP_016914931.1',
 'XP_061943455.1',
 'XP_016904254.1',
 'XP_028521994.2',
 'XP_061932385.1',
 'XP_016914064.1',
 'XP_016921933.1',
 'XP_028521838.1',
 'XP_061942778.1',
 'XP_016919703.1',
 'XP_016918557.1',
 'XP_061938380.1',
 'XP_061933000.1',
 'XP_028523336.1',
 'XP_061939003.1',
 'XP_016912546.1',
 'XP_061934704.1',
 'XP_061931424.1',
 'XP_016911890.2',
 'XP_061933087.1',
 'XP_016908683.1',
 'XP_016921020.1',
 'XP_016916873.1',
 'XP_016915649.2',
 'XP_061936160.1',
 'XP_061927065.1',
 'XP_061938646.1',
 'XP_016919891.1',
 'XP_061936761.1',
 'XP_016914540.1',
 'XP_061940467.1',
 'XP_061932647.1',
 'XP_016922418.1',
 'XP_016907989.1',
 'XP_016919613.1',
 'XP_016913609.1',
 'XP_061934092.1',
 'XP_061927685.1',
 'XP_061941535.1',
 'XP_061927672.1',
 'XP_016908180.1',
 'XP_061936489.1',
 'XP_016908132.2',
 'XP_061941672.1',
 'XP_028525475.1',
 'XP_016915387.1',
 'XP_061933148.1',
 'XP_016922189.2',
 'XP_061934888.1',
 'XP_016907279.1',
 'XP_061934583.1',
 'XP_061937755.1',
 'XP_016907928.1',
 'XP_016921426.1',
 'XP_016904087.1',
 'XP_016908651.1',
 'XP_061939417.1',
 'XP_061942584.1',
 'XP_061933620.1',
 'XP_061935420.1',
 'XP_061933810.1',
 'XP_016904969.1',
 'XP_061928017.1',
 'XP_016920537.1',
 'XP_061930252.1',
 'XP_016922571.2',
 'XP_028523962.1',
 'XP_061940403.1',
 'XP_016914902.1',
 'XP_016906530.1',
 'XP_028520798.1',
 'XP_061933970.1',
 'XP_061928561.1',
 'XP_016913045.2',
 'XP_016907590.2',
 'XP_061940333.1',
 'XP_061932306.1',
 'XP_061935328.1',
 'XP_061940973.1',
 'XP_061939333.1',
 'XP_061937298.1',
 'XP_016917763.1',
 'XP_016921129.1',
 'XP_061938047.1',
 'XP_061927054.1',
 'XP_061940365.1',
 'XP_061936511.1',
 'XP_016915527.1',
 'XP_061942802.1',
 'XP_016921548.1',
 'XP_061942452.1',
 'XP_061931099.1',
 'XP_061936069.1',
 'XP_061930837.1',
 'XP_061936153.1',
 'XP_061939015.1',
 'XP_016910612.1',
 'XP_061932902.1',
 'XP_061937371.1',
 'XP_016914517.1',
 'XP_016909693.1',
 'XP_061931356.1',
 'XP_061941160.1',
 'XP_016921359.1',
 'XP_028524637.1',
 'XP_016922511.1',
 'XP_016918434.2',
 'XP_061928851.1',
 'XP_061928425.1',
 'XP_061936992.1',
 'XP_061934870.1',
 'XP_061929063.1',
 'XP_061929263.1',
 'XP_061927501.1',
 'XP_061928295.1',
 'XP_016906105.1',
 'XP_061935091.1',
 'XP_028523289.1',
 'XP_061929106.1',
 'XP_061927912.1',
 'XP_061936165.1',
 'XP_061941603.1',
 'XP_061943463.1',
 'XP_061939214.1',
 'XP_061932984.1',
 'XP_061936860.1',
 'XP_016916193.2',
 'XP_061929626.1',
 'XP_061933214.1',
 'XP_061929198.1',
 'XP_016915167.1',
 'XP_016909642.1',
 'XP_016921367.1',
 'XP_061941777.1',
 'XP_061931188.1',
 'XP_016910458.2',
 'XP_061940042.1',
 'XP_061937466.1',
 'XP_061929814.1',
 'XP_061933451.1',
 'XP_061939086.1',
 'XP_061930410.1',
 'XP_016914297.1',
 'XP_016915641.1',
 'XP_061929993.1',
 'XP_061939844.1',
 'XP_028520673.1',
 'XP_016916349.2',
 'XP_028523560.1',
 'XP_028521114.1',
 'XP_061934953.1',
 'XP_061943231.1',
 'XP_016918348.1',
 'XP_061943342.1',
 'XP_061939377.1',
 'XP_061929435.1',
 'XP_061936306.1',
 'XP_061941964.1',
 'XP_028524522.1',
 'XP_028525203.2',
 'XP_016911280.1',
 'XP_016921497.1',
 'XP_061935073.1',
 'XP_016915010.1',
 'XP_016922949.1',
 'XP_061941693.1',
 'XP_061929093.1',
 'XP_061927132.1',
 'XP_061938354.1',
 'XP_028522695.2',
 'XP_061933483.1',
 'XP_061933464.1',
 'XP_061939053.1',
 'XP_016921698.1',
 'XP_016909493.1',
 'XP_061931624.1',
 'XP_016916685.2',
 'XP_016922099.1',
 'XP_016920479.1',
 'XP_061936082.1',
 'XP_061933660.1',
 'XP_061939126.1',
 'XP_061940212.1',
 'XP_061939826.1',
 'XP_061935156.1',
 'XP_061930783.1',
 'XP_061929453.1',
 'XP_016917504.1',
 'XP_061927032.1',
 'XP_061931341.1',
 'XP_061938117.1',
 'XP_061927780.1',
 'XP_061938574.1',
 'XP_016919910.1',
 'XP_016906387.1',
 'XP_061930172.1',
 'XP_016914897.1',
 'XP_061936276.1',
 'XP_016916125.2',
 'XP_061927360.1',
 'XP_016910600.1',
 'XP_028522480.1',
 'XP_061935274.1',
 'XP_061939906.1',
 'XP_061942058.1',
 'XP_016905173.2',
 'XP_016908505.1',
 'XP_061930466.1',
 'XP_061929624.1',
 'XP_061932790.1',
 'XP_061927792.1',
 'XP_016920138.1',
 'XP_028522817.1',
 'XP_061930040.1',
 'XP_061927521.1',
 'XP_016918457.2',
 'XP_061934906.1',
 'XP_016918230.1',
 'XP_061942243.1',
 'XP_061940836.1',
 'XP_061937179.1',
 'XP_061941431.1',
 'XP_016907619.1',
 'XP_016914714.1',
 'XP_016907864.1',
 'XP_061927568.1',
 'XP_028523355.1',
 'XP_028525259.1',
 'XP_061936611.1',
 'XP_016914844.1',
 'XP_016906925.1',
 'XP_061939819.1',
 'XP_061941429.1',
 'XP_061932881.1',
 'XP_061937593.1',
 'XP_061928247.1',
 'XP_061941708.1',
 'XP_061943320.1',
 'XP_061927444.1',
 'XP_061927788.1',
 'XP_028524740.1',
 'XP_061930632.1',
 'XP_061942330.1',
 'XP_061932312.1',
 'XP_061940640.1',
 'XP_061941475.1',
 'XP_028525706.1',
 'XP_016916505.1',
 'XP_016913496.1',
 'XP_061938488.1',
 'XP_016905574.2',
 'XP_016908777.1',
 'XP_016908970.1',
 'XP_016913523.1',
 'XP_061932776.1',
 'XP_061939049.1',
 'XP_061941812.1',
 'XP_016922433.1',
 'XP_016920134.1',
 'XP_028523689.1',
 'XP_016908990.1',
 'XP_061930812.1',
 'XP_016914226.1',
 'XP_061933034.1',
 'XP_061938599.1',
 'XP_061927599.1',
 'XP_061936401.1',
 'XP_016906984.1',
 'XP_061940713.1',
 'XP_061933191.1',
 'XP_061928659.1',
 'XP_061936918.1',
 'XP_061943028.1',
 'XP_028523077.1',
 'XP_016915784.1',
 'XP_061928242.1',
 'XP_028520472.1',
 'XP_061935171.1',
 'XP_061938176.1',
 'XP_061933940.1',
 'XP_016911772.1',
 'XP_061933360.1',
 'XP_061941123.1',
 'XP_016912975.1',
 'XP_061938119.1',
 'XP_016915561.1',
 'XP_028520400.2',
 'XP_061929306.1',
 'XP_061928166.1',
 'XP_061940979.1',
 'XP_016919555.1',
 'XP_061936948.1',
 'XP_016914287.1',
 'XP_016911627.1',
 'XP_016921077.1',
 'XP_061930269.1',
 'XP_016911681.1',
 'XP_016909059.1',
 'XP_016921245.1',
 'XP_061939627.1',
 'XP_061929722.1',
 'XP_061942074.1',
 'XP_061938475.1',
 'XP_061935918.1',
 'XP_016904294.1',
 'XP_061938862.1',
 'XP_061940907.1',
 'XP_061933983.1',
 'XP_061931773.1',
 'XP_016907586.1',
 'XP_028524809.2',
 'XP_061941051.1',
 'XP_016919148.1',
 'XP_061934574.1',
 'XP_016904806.1',
 'XP_061933788.1',
 'XP_061940386.1',
 'XP_016916210.2',
 'XP_028525758.1',
 'XP_061935705.1',
 'XP_061943402.1',
 'XP_061927816.1',
 'XP_061928801.1',
 'XP_028522584.1',
 'XP_061935755.1',
 'XP_016905391.1',
 'XP_061930820.1',
 'XP_016910448.2',
 'XP_061928896.1',
 'XP_061938184.1',
 'XP_016904036.1',
 'XP_016914653.1',
 'XP_061931486.1',
 'XP_061940176.1',
 'XP_016907498.1',
 'XP_061929688.1',
 'XP_061932797.1',
 'XP_061938090.1',
 'XP_016922110.1',
 'XP_016906266.1',
 'XP_016922139.1',
 'XP_016918232.1',
 'XP_016912717.1',
 'XP_061927160.1',
 'XP_028523754.1',
 'XP_016913615.1',
 'XP_061942551.1',
 'XP_016905949.1',
 'XP_061934755.1',
 'XP_028524650.1',
 'XP_016907595.2',
 'XP_061929631.1',
 'XP_061927727.1',
 'XP_061939075.1',
 'XP_061935207.1',
 'XP_016905698.2',
 'XP_061936851.1',
 'XP_061935789.1',
 'XP_061932381.1',
 'XP_016919853.2',
 'XP_016904014.3',
 'XP_061932391.1',
 'XP_061928325.1',
 'XP_061943220.1',
 'XP_061929376.1',
 'XP_028524728.1',
 'XP_061930290.1',
 'XP_016922610.1',
 'XP_061936564.1',
 'XP_061940114.1',
 'XP_061939076.1',
 'XP_016913405.1',
 'XP_016919275.1',
 'XP_028522449.2',
 'XP_061940969.1',
 'XP_016911510.1',
 'XP_061943014.1',
 'XP_061928007.1',
 'XP_061932299.1',
 'XP_061932388.1',
 'XP_061937223.1',
 'XP_016921792.2',
 'XP_061939725.1',
 'XP_016909652.2',
 'XP_016910332.1',
 'XP_061942462.1',
 'XP_061939742.1',
 'XP_016920404.1',
 'XP_016921573.1',
 'XP_016912077.1',
 'XP_061938077.1',
 'XP_028524640.2',
 'XP_016912383.1',
 'XP_061938057.1',
 'XP_016920957.1',
 'XP_016913198.1',
 'XP_016919062.1',
 'XP_028520284.1',
 'XP_061942019.1',
 'XP_061941038.1',
 'XP_061929206.1',
 'XP_016914021.1',
 'XP_028521127.2',
 'XP_061940304.1',
 'XP_061935772.1',
 'XP_061937400.1',
 'XP_061926904.1',
 'XP_061929926.1',
 'XP_061942371.1',
 'XP_061931646.1',
 'XP_061943161.1',
 'XP_061936322.1',
 'XP_016911846.1',
 'XP_061941543.1',
 'XP_016919559.1',
 'XP_016913278.1',
 'XP_016909883.2',
 'XP_061939213.1',
 'XP_061932247.1',
 'XP_016908385.2',
 'XP_061938606.1',
 'XP_061939841.1',
 'XP_016920980.2',
 'XP_016920583.1',
 'XP_061932836.1',
 'XP_016909252.2',
 'XP_061928123.1',
 'XP_028522688.1',
 'XP_061942514.1',
 'XP_061931027.1',
 'XP_061941637.1',
 'XP_016904349.1',
 'XP_016917007.1',
 'XP_061937357.1',
 'XP_061939283.1',
 'XP_028524517.1',
 'XP_061937650.1',
 'XP_016916918.1',
 'XP_061928086.1',
 'XP_016914054.1',
 'XP_016915133.2',
 'XP_061929938.1',
 'XP_061942628.1',
 'XP_061931963.1',
 'XP_061939958.1',
 'XP_061939523.1',
 'XP_061937131.1',
 'XP_061934157.1',
 'XP_061931954.1',
 'XP_016921402.1',
 'XP_061932433.1',
 'XP_016909182.1',
 'XP_061931384.1',
 'XP_061930714.1',
 'XP_028520979.1',
 'XP_061933623.1',
 'XP_016917324.1',
 'XP_061940329.1',
 'XP_016917333.1',
 'XP_061942080.1',
 'XP_028520628.1',
 'XP_028520584.1',
 'XP_016914104.1',
 ...}

faa 中的 header 都会出现在 GTF 的 protein_id 列中吗？

In [11]:
pid_set = set(Acer_pid_gid["protein_id"])
print(len(pid_set))
print(len(header_set))
print(len(pid_set & header_set))
print(pid_set - header_set)

29189
29188
29188
{nan}

是的。faa 中的 header 都会出现在 GTF 的 protein_id 列中

In [17]:
# for long_name in Acer_faa.keys():
#     pid_short_header = long_name.split(' ')[0]
#     gid = Acer_pid_gid.loc[Acer_pid_gid["protein_id"] == pid_short_header, "gene_id"].iloc[0]
#     new_header = long_name.replace(pid_short_header, gid, 1)
#     print(new_header)

In [18]:
with open("./corrected/Acer_corrected.faa", "w") as fout:
    for long_name in Acer_faa.keys():
        pid_short_header = long_name.split(' ')[0]
        gid = Acer_pid_gid.loc[Acer_pid_gid["protein_id"] == pid_short_header, "gene_id"].iloc[0]
        new_header = long_name.replace(pid_short_header, gid, 1)
        seq = Acer_faa[long_name][:].seq

        fout.write(f">{new_header}\n")
        fout.write(seq + "\n")